<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dawn, Lizao Zhuang (r0914937)">
<meta name="keywords" content="Natural History, Pliny the Elder, Spatial Humanities, Indo-Roman, Indo-Mediterranean">

<title>Mapping India in Pliny the Elder’s Natural History</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="NHthesis_structure_files/libs/clipboard/clipboard.min.js"></script>
<script src="NHthesis_structure_files/libs/quarto-html/quarto.js"></script>
<script src="NHthesis_structure_files/libs/quarto-html/popper.min.js"></script>
<script src="NHthesis_structure_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="NHthesis_structure_files/libs/quarto-html/anchor.min.js"></script>
<link href="NHthesis_structure_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="NHthesis_structure_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="NHthesis_structure_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="NHthesis_structure_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="NHthesis_structure_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-introduction" id="toc-sec-introduction" class="nav-link active" data-scroll-target="#sec-introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul>
  <li><a href="#natural-history-and-its-complexity" id="toc-natural-history-and-its-complexity" class="nav-link" data-scroll-target="#natural-history-and-its-complexity"><span class="header-section-number">1.1</span> <em>Natural History</em> and its complexity</a></li>
  <li><a href="#spatial-perstpective-in-natural-history" id="toc-spatial-perstpective-in-natural-history" class="nav-link" data-scroll-target="#spatial-perstpective-in-natural-history"><span class="header-section-number">1.2</span> Spatial perstpective in <em>Natural History</em></a></li>
  <li><a href="#text-source-for-the-study" id="toc-text-source-for-the-study" class="nav-link" data-scroll-target="#text-source-for-the-study"><span class="header-section-number">1.3</span> Text source for the study</a></li>
  </ul></li>
  <li><a href="#sec-research_question" id="toc-sec-research_question" class="nav-link" data-scroll-target="#sec-research_question"><span class="header-section-number">2</span> Research Question</a>
  <ul>
  <li><a href="#prominent-mentioned-places-in-natural-history" id="toc-prominent-mentioned-places-in-natural-history" class="nav-link" data-scroll-target="#prominent-mentioned-places-in-natural-history"><span class="header-section-number">2.1</span> Prominent mentioned places in <em>Natural History</em></a></li>
  <li><a href="#why-india" id="toc-why-india" class="nav-link" data-scroll-target="#why-india"><span class="header-section-number">2.2</span> Why India?</a></li>
  <li><a href="#india-related-text-as-a-case-study" id="toc-india-related-text-as-a-case-study" class="nav-link" data-scroll-target="#india-related-text-as-a-case-study"><span class="header-section-number">2.3</span> India-related text as a case study</a></li>
  </ul></li>
  <li><a href="#sec-methodology" id="toc-sec-methodology" class="nav-link" data-scroll-target="#sec-methodology"><span class="header-section-number">3</span> Methodology</a>
  <ul>
  <li><a href="#workflow" id="toc-workflow" class="nav-link" data-scroll-target="#workflow"><span class="header-section-number">3.1</span> Workflow</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation"><span class="header-section-number">3.2</span> Data preparation</a>
  <ul class="collapse">
  <li><a href="#html-scraping-from-topostext" id="toc-html-scraping-from-topostext" class="nav-link" data-scroll-target="#html-scraping-from-topostext"><span class="header-section-number">3.2.1</span> HTML scraping from TOPOSText</a></li>
  <li><a href="#filtered-dataset-of-india-related-text" id="toc-filtered-dataset-of-india-related-text" class="nav-link" data-scroll-target="#filtered-dataset-of-india-related-text"><span class="header-section-number">3.2.2</span> Filtered dataset of “India-related text”</a></li>
  <li><a href="#data-completeness-check" id="toc-data-completeness-check" class="nav-link" data-scroll-target="#data-completeness-check"><span class="header-section-number">3.2.3</span> Data completeness check</a></li>
  <li><a href="#preprocessing-of-texts" id="toc-preprocessing-of-texts" class="nav-link" data-scroll-target="#preprocessing-of-texts"><span class="header-section-number">3.2.4</span> Preprocessing of texts</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#data-analysis" id="toc-data-analysis" class="nav-link" data-scroll-target="#data-analysis"><span class="header-section-number">4</span> Data Analysis</a>
  <ul>
  <li><a href="#place-name-distribution-in-india-related-text" id="toc-place-name-distribution-in-india-related-text" class="nav-link" data-scroll-target="#place-name-distribution-in-india-related-text"><span class="header-section-number">4.1</span> Place name distribution in India-related text</a></li>
  <li><a href="#word-frequency-and-collocating-bi-grams" id="toc-word-frequency-and-collocating-bi-grams" class="nav-link" data-scroll-target="#word-frequency-and-collocating-bi-grams"><span class="header-section-number">4.2</span> Word frequency and collocating bi-grams</a></li>
  <li><a href="#topic-modeling" id="toc-topic-modeling" class="nav-link" data-scroll-target="#topic-modeling"><span class="header-section-number">4.3</span> Topic modeling</a></li>
  <li><a href="#network-analysis-for-named-entity" id="toc-network-analysis-for-named-entity" class="nav-link" data-scroll-target="#network-analysis-for-named-entity"><span class="header-section-number">4.4</span> Network analysis for Named Entity</a>
  <ul class="collapse">
  <li><a href="#person-name-annotationtag-retrieve" id="toc-person-name-annotationtag-retrieve" class="nav-link" data-scroll-target="#person-name-annotationtag-retrieve"><span class="header-section-number">4.4.1</span> Person name annotation/tag retrieve</a></li>
  <li><a href="#network-graph-generation" id="toc-network-graph-generation" class="nav-link" data-scroll-target="#network-graph-generation"><span class="header-section-number">4.4.2</span> Network graph generation</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#sec-conclusions" id="toc-sec-conclusions" class="nav-link" data-scroll-target="#sec-conclusions"><span class="header-section-number">5</span> Conclusions</a>
  <ul>
  <li><a href="#comprehension-of-india-in-the-narrative" id="toc-comprehension-of-india-in-the-narrative" class="nav-link" data-scroll-target="#comprehension-of-india-in-the-narrative"><span class="header-section-number">5.1</span> Comprehension of “India” in the narrative</a></li>
  <li><a href="#distant-reading-as-a-method" id="toc-distant-reading-as-a-method" class="nav-link" data-scroll-target="#distant-reading-as-a-method"><span class="header-section-number">5.2</span> Distant reading as a method</a></li>
  <li><a href="#reflection-and-limitation" id="toc-reflection-and-limitation" class="nav-link" data-scroll-target="#reflection-and-limitation"><span class="header-section-number">5.3</span> Reflection and limitation</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">6</span> References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="NHthesis_structure.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Mapping India in Pliny the Elder’s <em>Natural History</em></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dawn, Lizao Zhuang (r0914937) </p>
          </div>
  </div>
    
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="abstract-title">Abstract</div>
    this is an abstract
  </div>
</div>

</header>

<section id="sec-introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="sec-introduction"><span class="header-section-number">1</span> Introduction</h2>
<section id="natural-history-and-its-complexity" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="natural-history-and-its-complexity"><span class="header-section-number">1.1</span> <em>Natural History</em> and its complexity</h3>
<p>Pliny the Elder’s <em>Natural History</em> is widely recognized as the earliest encyclopedia in the world, manifesting a pioneering effort in comprehensively cataloging the vast array of human knowledge from that era.</p>
<p>The work is thematically divided into 37 books, covering a diverse range of subjects including astronomy, geography, zoology, botany, medicine, and more. Pliny meticulously consulted a wide range of Greek and Roman references, totaling approximately 2,000 volumes<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, and interwove his own literary interpretation or comments to the narratives.</p>
<p>Despite the carefully designed knowledge-ordering framework <span class="citation" data-cites="lao2016">(<a href="#ref-lao2016" role="doc-biblioref">Lao 2016</a>)</span>, scholars have observed a paradoxical complexity in <em>Natural History</em>, evident in its linguistic style, narrative approach, and use of references. The work compiles inconsistent toponyms from Greek and Latin, includes digressions in descriptions <span class="citation" data-cites="roller2022">(<a href="#ref-roller2022" role="doc-biblioref">Roller 2022</a>)</span>, and exhibits changes in vocabularies and sentence structures <span class="citation" data-cites="pinkster2005">(<a href="#ref-pinkster2005" role="doc-biblioref">Pinkster 2005</a>)</span>. However, it is precisely this complexity that makes the work more fascinating and not only a valuable source of the knowledge and worldview of the ancient world, but also a gateway into Pliny’s conceptualization, imagination, and even the prevailing imperial ideology of that time.</p>
<p>The complexity and interconnectivity of the general structure of <em>Natural History</em> are further highlighted in different aspects by refreshing approaches. For the content organisation, <span class="citation" data-cites="healy1999">Healy (<a href="#ref-healy1999" role="doc-biblioref">1999</a>)</span> advocated Pliny’s original contribution in revealing the technology and science engagement of the Rome Empire. Taking the historical, political and linguistic context into consideration, he found that in addition to providing informative descriptions of natural phenomena and scientific experiments, Pliny also developed the scientific language in Latin through his work. And <span class="citation" data-cites="naas2002">Naas (<a href="#ref-naas2002" role="doc-biblioref">2002</a>)</span> discussed how Pliny formulated the diverse materials into his encyclopaedic structure, revealing the work’s multifaceted nature as an epistemological, ideological, and moral project. Analysing Pliny’s employment of the historical exemplum in the work, <span class="citation" data-cites="schultze2011">Schultze (<a href="#ref-schultze2011" role="doc-biblioref">2011</a>)</span> argued how that literary device directed and teased the readers as well as established a profound connection between human beings and the entire spectrum of nature in <em>Natural History</em>.</p>
<p>In addition to the close reading methods used in the above analyses of the context and references in <em>Natural History</em>, <span class="citation" data-cites="rydberg-cox2021">Rydberg-Cox (<a href="#ref-rydberg-cox2021" role="doc-biblioref">2021</a>)</span> employed network analysis method with different metrics to map the interrelationships between Pliny’s sources and the topics discussed in the work. Furthermore, <span class="citation" data-cites="fantoli2022">Fantoli (<a href="#ref-fantoli2022" role="doc-biblioref">2022</a>)</span> presented a comparative study of book 2 of <em>Natural History</em> and book 7 of Seneca’s work <em>Natural Questions</em>, both of which are astronomy sections in the Latin classics about nature. Her study utilized statistical method to analyse variations in their discourse distribution, and identified Pliny’s unique stylistic features. The encyclopaedic authorial intent shown in <em>Natural History</em> is also vindicated through correspondence and tree analysis. These two studies demonstrate how distant reading methodologies offer novel insights into our understanding of the ancient treatises.</p>
<p>In addition to the contextual and referential analyses about <em>Natural History</em>, <span class="citation" data-cites="rydberg-cox2021">Rydberg-Cox (<a href="#ref-rydberg-cox2021" role="doc-biblioref">2021</a>)</span> employed network analysis techniques, applying various metrics to illustrate the connections between Pliny’s sources and the topics discussed in the work. Furthermore, <span class="citation" data-cites="fantoli2022">Fantoli (<a href="#ref-fantoli2022" role="doc-biblioref">2022</a>)</span> conducted a comparative examination of book 2 of <em>Natural History</em> and book 7 of Seneca’s <em>Natural Questions</em>, both focused on astronomy as part of the Latin classics about nature. Statistical methods were applied to investigate variations in their discursive distribution, effectively identifying Pliny’s distinctive stylistic attributes. Moreover, the encyclopaedic authorial intent evident in <em>Natural History</em> is validated through correspondence and tree analysis. These studies collectively showcase how distant reading methodologies offer novel insights into our understanding of ancient treatises.</p>
</section>
<section id="spatial-perstpective-in-natural-history" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="spatial-perstpective-in-natural-history"><span class="header-section-number">1.2</span> Spatial perstpective in <em>Natural History</em></h3>
<p>As pointed out by <span class="citation" data-cites="beagon2011">Beagon (<a href="#ref-beagon2011" role="doc-biblioref">2011</a>)</span>, differentiating from his predecessors, Pliny showed a “terrestrial curiosity” in <em>Natural History</em>, emphasising recognition of the physical, material world. In this regard, the vision of geography plays a pivotal role in distributing information, knowledge, and events throughout <em>Natural History</em>.</p>
<p>Drawing from the long-established topographical and ethnographic traditions, Pliny seamlessly connects volumes dedicated to geography (books 3-6) with broader elements, activities, and cultural, historical, and societal contexts<span class="citation" data-cites="roller2022">(<a href="#ref-roller2022" role="doc-biblioref">Roller 2022</a>)</span>, exemplified in his portrayal of exotic plants, communities’ habitats, imperial expeditions, and trade products. In other words, geographical names that occurred in each book of <em>Natural History</em> served as signposts guiding readers through diverse lands, shedding light on how Pliny and his contemporaries perceived and conceptualized the world around them.</p>
<p>A normalized frequency of place name occurrence in the work is calculated as the ratio of counts of the occurrences of place names in each book to the word lengths of the book (<a href="#tbl-place_book_distribution">Table&nbsp;1</a>). The bar chart (<a href="#fig-place_distribution">Figure&nbsp;1</a>) depicts the comparison of the distribution of place names in the books of <em>Natural History</em>. The observation aligns with the content structure of <em>Natural History</em>, that books 3-6 centred around the themes of “geography and ethnography”, contain the most mentions of location names, and place names are also frequently mentioned in books about agriculture and horticulture (book 12-14), aquatic life (book 31), and mining and mineralogy (book 34-37).</p>
<div class="cell" data-df-print="tibble" data-execution_count="2">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<div id="tbl-place_book_distribution" class="anchored">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Table&nbsp;1: Normalized distribution of place names in <em>Natural History</em></caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Total_length</th>
<th data-quarto-table-cell-role="th">Place_count</th>
<th data-quarto-table-cell-role="th">Place_freq</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Book</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>2778</td>
<td>1</td>
<td>0.000360</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>30570</td>
<td>406</td>
<td>0.013281</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>18037</td>
<td>1007</td>
<td>0.055830</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>15434</td>
<td>1309</td>
<td>0.084813</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>18872</td>
<td>1112</td>
<td>0.058923</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6</td>
<td>27891</td>
<td>1012</td>
<td>0.036284</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7</td>
<td>21204</td>
<td>225</td>
<td>0.010611</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">8</td>
<td>24176</td>
<td>185</td>
<td>0.007652</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">9</td>
<td>19197</td>
<td>140</td>
<td>0.007293</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">10</td>
<td>20816</td>
<td>121</td>
<td>0.005813</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">11</td>
<td>27345</td>
<td>77</td>
<td>0.002816</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">12</td>
<td>13906</td>
<td>188</td>
<td>0.013519</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">13</td>
<td>13243</td>
<td>164</td>
<td>0.012384</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">14</td>
<td>15277</td>
<td>189</td>
<td>0.012372</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">15</td>
<td>14552</td>
<td>135</td>
<td>0.009277</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">16</td>
<td>25442</td>
<td>180</td>
<td>0.007075</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">17</td>
<td>29387</td>
<td>82</td>
<td>0.002790</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">18</td>
<td>35850</td>
<td>222</td>
<td>0.006192</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">19</td>
<td>18822</td>
<td>146</td>
<td>0.007757</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">20</td>
<td>22743</td>
<td>21</td>
<td>0.000923</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">21</td>
<td>17896</td>
<td>95</td>
<td>0.005308</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">22</td>
<td>16491</td>
<td>24</td>
<td>0.001455</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">23</td>
<td>15764</td>
<td>17</td>
<td>0.001078</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">24</td>
<td>17491</td>
<td>56</td>
<td>0.003202</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25</td>
<td>16734</td>
<td>85</td>
<td>0.005079</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">26</td>
<td>15448</td>
<td>35</td>
<td>0.002266</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">27</td>
<td>12444</td>
<td>40</td>
<td>0.003214</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">28</td>
<td>26476</td>
<td>28</td>
<td>0.001058</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">29</td>
<td>13976</td>
<td>31</td>
<td>0.002218</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">30</td>
<td>14395</td>
<td>23</td>
<td>0.001598</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">31</td>
<td>12204</td>
<td>222</td>
<td>0.018191</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">32</td>
<td>14635</td>
<td>76</td>
<td>0.005193</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">33</td>
<td>17946</td>
<td>113</td>
<td>0.006297</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">34</td>
<td>18972</td>
<td>193</td>
<td>0.010173</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">35</td>
<td>21283</td>
<td>277</td>
<td>0.013015</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">36</td>
<td>21295</td>
<td>357</td>
<td>0.016764</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">37</td>
<td>22255</td>
<td>282</td>
<td>0.012671</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</div>
<div class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-place_distribution" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;1: Normalized distribution of place names in <em>Natural History</em></figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-place_distribution-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="text-source-for-the-study" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="text-source-for-the-study"><span class="header-section-number">1.3</span> Text source for the study</h3>
<p><em>Natural History</em> is originally in Latin. For the purpose of this study, an English translation conducted by Henry T. Riley (1816-1878) and John Bostock (1773-1846), first published in 1855, is utilized. The translated text is obtained in a digitized version from the <a href="https://topostext.org/the-project">TOPOSText project</a>, having been sourced from the Perseus Project and governed by a Creative Commons Attribution-Share-Alike 3.0 U.S. License.</p>
<p>Annotations of proper names, place names and their corresponding coordinates are available together with the text of <em>Natural History</em> (<a href="https://topostext.org/work/148">Book1-11</a>, <a href="https://topostext.org/work/153">Book12-37</a>) on <a href="https://topostext.org/the-project">TOPOSText project</a>. This invaluable resource allows for creating a dataset that includes both the textual contents and geographical annotations, which can be utilized to investigate the distribution of place names in the entire work and examine the frequencies and patterns of geography-related content.</p>
<p>The extension of the extracted corpora and the workflow of the extraction will be further explained in the Methodology chapter (<a href="#sec-methodology">Section&nbsp;3</a>).</p>
</section>
</section>
<section id="sec-research_question" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="sec-research_question"><span class="header-section-number">2</span> Research Question</h2>
<section id="prominent-mentioned-places-in-natural-history" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="prominent-mentioned-places-in-natural-history"><span class="header-section-number">2.1</span> Prominent mentioned places in <em>Natural History</em></h3>
<div class="cell" data-execution_count="32">
<div class="cell-output cell-output-display">
<p>Based on the geographical annotations in <em>Natural History</em> provided by the TOPOSText, there are 2052 unique places mentioned in <em>Natural History</em>.</p>
</div>
</div>
<p>The top 20 most frequently mentioned place names (as 1% of the total) in <em>Natural History</em> is shown in <a href="#tbl-topplace">Table&nbsp;2</a>.</p>
<div class="cell" data-df-print="tibble" data-execution_count="34">
<div class="cell-output cell-output-display" data-execution_count="34">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<div id="tbl-topplace" class="anchored">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Table&nbsp;2: Top 20 mentioned place names in Natural History</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ToposText_ID</th>
<th data-quarto-table-cell-role="th">Place_Name</th>
<th data-quarto-table-cell-role="th">Lat</th>
<th data-quarto-table-cell-role="th">Long</th>
<th data-quarto-table-cell-role="th">Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1687</td>
<td>https://topostext.org/place/406163RIta</td>
<td>Italy</td>
<td>40.6000</td>
<td>16.30000</td>
<td>292</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2034</td>
<td>https://topostext.org/place/419125PRom</td>
<td>Rome</td>
<td>41.8910</td>
<td>12.48600</td>
<td>269</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">52</td>
<td>https://topostext.org/place/271307REgy</td>
<td>Egypt</td>
<td>27.1000</td>
<td>30.70000</td>
<td>261</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">82</td>
<td>https://topostext.org/place/300740RInd</td>
<td>India</td>
<td>30.0000</td>
<td>74.00000</td>
<td>167</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">57</td>
<td>https://topostext.org/place/280400RAra</td>
<td>Arabia</td>
<td>28.0000</td>
<td>40.00000</td>
<td>123</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">320</td>
<td>https://topostext.org/place/355390RSyr</td>
<td>Syria</td>
<td>35.5000</td>
<td>39.00000</td>
<td>109</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">255</td>
<td>https://topostext.org/place/350330RCyp</td>
<td>Cyprus</td>
<td>35.0000</td>
<td>33.00000</td>
<td>85</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">109</td>
<td>https://topostext.org/place/312301WNil</td>
<td>Nile</td>
<td>30.0918</td>
<td>31.23130</td>
<td>85</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2282</td>
<td>https://topostext.org/place/441073LAlp</td>
<td>Alps</td>
<td>44.1420</td>
<td>7.34300</td>
<td>82</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">766</td>
<td>https://topostext.org/place/376145RSic</td>
<td>Sicily</td>
<td>37.6000</td>
<td>14.50000</td>
<td>71</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">275</td>
<td>https://topostext.org/place/352252IKre</td>
<td>Crete</td>
<td>35.2052</td>
<td>25.18360</td>
<td>64</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>https://topostext.org/place/130350REth</td>
<td>Ethiopia</td>
<td>13.0100</td>
<td>35.01000</td>
<td>58</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">417</td>
<td>https://topostext.org/place/364282IRho</td>
<td>Rhodes</td>
<td>36.4408</td>
<td>28.22440</td>
<td>56</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">966</td>
<td>https://topostext.org/place/380237PAth</td>
<td>Athens</td>
<td>37.9718</td>
<td>23.72793</td>
<td>56</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2043</td>
<td>https://topostext.org/place/419125SCap</td>
<td>Capitol</td>
<td>41.8933</td>
<td>12.48300</td>
<td>52</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">298</td>
<td>https://topostext.org/place/353403WEup</td>
<td>Euphrates</td>
<td>35.2791</td>
<td>40.27080</td>
<td>47</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2241</td>
<td>https://topostext.org/place/435335WPon</td>
<td>Pontus</td>
<td>43.5000</td>
<td>33.50000</td>
<td>47</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1839</td>
<td>https://topostext.org/place/411146RCam</td>
<td>Campania</td>
<td>41.1000</td>
<td>14.60000</td>
<td>46</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1480</td>
<td>https://topostext.org/place/397443RArm</td>
<td>Armenia</td>
<td>39.7020</td>
<td>44.29800</td>
<td>45</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">17</td>
<td>https://topostext.org/place/195390WEry</td>
<td>Red Sea</td>
<td>19.5000</td>
<td>39.00000</td>
<td>42</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">545</td>
<td>https://topostext.org/place/369103PCar</td>
<td>Carthage</td>
<td>36.8500</td>
<td>10.32000</td>
<td>42</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">602</td>
<td>https://topostext.org/place/370340RCil</td>
<td>Cilicia</td>
<td>37.0100</td>
<td>34.01000</td>
<td>42</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</div>
<p>The place names referenced in <em>Natural History</em> are geographically mapped, with each location marked on the map using its corresponding coordinates. A dot is assigned to represent a place, with the size and color of the dot reflecting the frequency of its mention in the work. The larger and darker the dot, the more frequently the place is referred to within the context of <em>Natural History</em>.</p>
<p>An intriguing observation from the output, as depicted in <a href="#fig-geonamemap_pdf">Figure&nbsp;2</a>, is the prominence of India, a region outside the Mediterranean, despite its high frequency of mentions.</p>
<div class="cell" data-execution_count="17">
<div class="cell-output cell-output-display" data-execution_count="17">
<div id="fig-geonamemap_pdf" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;2: Place name distribution map</figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-geonamemap_pdf-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="why-india" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="why-india"><span class="header-section-number">2.2</span> Why India?</h3>
<p>Geographically, India seems a distant and disconnected territory from the Roman Empire, lacking any direct aquatic or land routes with the Mediterranean region. However, the exotic curiosity Pliny attempted to integrate within his work, and the history of the Indo-roman trade relations, can be regarded as a broader context for the prominent mentioning of India in <em>Natural History</em>.</p>
<p>As suggested by <span class="citation" data-cites="murphy2003">(<a href="#ref-murphy2003" role="doc-biblioref">Murphy 2003</a>)</span>, the <em>mirabilia</em>, encompassing accounts of extraordinary landscapes, people, plants, and animals, assumes a substantial proportion within the books of <em>Natural History</em>. Pliny’s inclusion of such exotic elements not only catered to the prevailing curiosity of his Roman readers but also fostered a comparative perspective between distant locales, exemplified by his references to India, and their natural counterparts within Rome <span class="citation" data-cites="naas2011">(<a href="#ref-naas2011" role="doc-biblioref">Naas 2011</a>)</span>. Within a research framework of Roman Imperialism, the detailed portrayal of foreign lands, such as India, holds significant importance in shaping both Pliny’s and his contemporary Roman readers’ perception of their place within the global landscape <span class="citation" data-cites="pollard2009">(<a href="#ref-pollard2009" role="doc-biblioref">Pollard 2009</a>)</span>.</p>
<p>In addition, <em>Natural History</em> serves as a valuable reference for tracking the Indo-Mediterranean network of exchange <span class="citation" data-cites="pollard2009">(<a href="#ref-pollard2009" role="doc-biblioref">Pollard 2009</a>)</span>. Through the depiction of cities, ports, and rivers along the trade routes, the work provides substantive evidence of the flourishing trade relations between the Roman Empire and the Indian subcontinent <span class="citation" data-cites="neelis2011">(<a href="#ref-neelis2011" role="doc-biblioref">Neelis 2011</a>)</span>. The extensive exemplification of diverse commodities, such as gemstones, glass, spices, textiles, plants, and wine, along with the accounts of the currency <em>sestertii</em> involved in the merchandise exchange in the work shed lights to the compelling details and social and cultural implications of this long-distance trade <span class="citation" data-cites="szekely2006 pollard2009">(<a href="#ref-szekely2006" role="doc-biblioref">Székely 2006</a>; <a href="#ref-pollard2009" role="doc-biblioref">Pollard 2009</a>)</span>. Furthermore, the direct criticisms regarding the high cost of the luxury items imported from India imply both the magnitude of the trade volume and Pliny’s stance towards this commercial interaction <span class="citation" data-cites="neelis2011">(<a href="#ref-neelis2011" role="doc-biblioref">Neelis 2011</a>)</span>.</p>
</section>
<section id="india-related-text-as-a-case-study" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="india-related-text-as-a-case-study"><span class="header-section-number">2.3</span> India-related text as a case study</h3>
<p>In light of the observations and foundational research mentioned above, the present study centres its investigation on the spatial perspective within Pliny’s <em>Natural History</em>, focusing on the texts about India, seeking to delve into the discourse surrounding this region. To achieve this goal, distant reading methodologies, including statistical analysis, topic modelling, and social network analysis, are employed in the study.</p>
<p>The main aim of this study is to explore how India is described, and how the information about India is structured in <em>Natural History</em>, which may also contribute to a more profound comprehension of the inherent complexity and interconnectivity that permeates this monumental work.</p>
</section>
</section>
<section id="sec-methodology" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="sec-methodology"><span class="header-section-number">3</span> Methodology</h2>
<section id="workflow" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="workflow"><span class="header-section-number">3.1</span> Workflow</h3>
<p>The workflow for this study involves the following key stages:</p>
<p><strong>Data Collection</strong>:</p>
<p>As mentioned in the Introduction chapter (<a href="#sec-introduction">Section&nbsp;1</a>), the text employed for this study is obtained from the digitized English translation (by Henry T. Riley (1816-1878) and John Bostock (1773-1846)) of Pliny’s <em>Natural History</em> available on <a href="https://topostext.org/the-project">TOPOSText project</a>.</p>
<p>The two parts of <em>Natural History</em> (<a href="https://topostext.org/work/148">Book1-11</a>, <a href="https://topostext.org/work/153">Book12-37</a>) are scraped for their the textual contents together with the geographical annotation of the mentioned ancient places, and their book, chapter and paragraph affiliations with the function provided in <a href="https://www.crummy.com/software/BeautifulSoup/bs4/doc/">Beautiful Soup</a> library of Python.</p>
<p><strong>Data Preprocessing</strong>:</p>
<p>The information extracted from the HTML is structured into separate columns as <a href="https://pandas.pydata.org/">Pandas</a> dataframe, a dataframe for plain text of the entire work, and a dataframe for geographical-related text in <em>Natural History</em> with the geographical annotations are generated and stored in CSV format.</p>
<p>After a preliminary exploration, the research focus is narrowed down to India-related text in <em>Natural History</em>. Referring to the geographical territories in the scope of ancient Greek and Roman world <span class="citation" data-cites="talbert2000">(<a href="#ref-talbert2000" role="doc-biblioref">Talbert 2000b</a>)</span>, a dataframe for India-related text is filtered from the abovementioned dataframe for geographical-related text with the range of corresponding coordinates of Indian subcontinent in the era of <em>Natural History</em>. The flitered India-related text dataframe is also stored in CSV format.</p>
<p>The location names mentioned in the India-related text were checked manually for its completeness. The identified location names without annotation in TOPOSText were appended to the India-related text dataset.</p>
<p>Additionally, the textual contents in the datasets were preprocessed with tokenization, lemmatization and the exclusion of stop-words processes.</p>
<p><strong>Data Analysis</strong>:</p>
<p>Statistical analysis is conducted in the preliminary exploration of the extracted dataframes. A nomalized frequency of geographical name occurence in each book is calculated for an overview of the place name distribution in <em>Natural History</em>. And the top 1% prominently mentioned place names in the entire work are sorted out with the time of their occurencies. The specific attention on India-related text as a case study is drown from this initial observation.</p>
<p>In the analysis of the India-related text (target corpus) in <em>Natural History</em>, three analysis methods are employed:</p>
<ol type="1">
<li><p>Word frequency and collocation analysis: single word frequency and bi-gram collocation of the target corpus are measured with the functions in <a href="https://www.nltk.org/">NLTK</a> package for an overview of the common word patterns relating to India in <em>Natural History</em>.</p></li>
<li><p>Topic modelling: <a href="https://radimrehurek.com/gensim/">Genism</a> library is used for semantic vectorization and implemetion of Latent Dirichlet Allocation (LDA) model for the topic modelling of the target corpus, and the library of <a href="https://pyldavis.readthedocs.io/en/latest/index.htmlgenism">pyLDAvis</a> is utilized for an interactive visualisation. The output of this method shows the potential topics in the India-related text in <em>Natural History</em>.</p></li>
<li><p>Network analysis for named entities: Person names mentioned in the India-related text are retrieved from annotaions on TOPOSText. Person and place names occured in the target corpus are extracted as nodes together with their affiliated book numbers, and the co-occurence between the nodes are counted as edges for network analysis. The output of this method is a graph showing the clusters of the nodes in the target corpus, indicating the structure of the content related to India in <em>Natural History</em>.</p></li>
</ol>
<p><strong>Interpretation and Conclusion</strong>:</p>
<p>The workflow and parameter setting of each research method are explained at the beginning of each analysis section. The results aquired from each method are interpreted with a dialouge to the broader literature and close reading of the related text.</p>
<p>In the Conclusion chapter (<a href="#sec-conclusions">Section&nbsp;5</a>), the findings are illustrated comprehensively as a response to the research questions. And the limitations of the methods are discussed and evaluated.</p>
</section>
<section id="data-preparation" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="data-preparation"><span class="header-section-number">3.2</span> Data preparation</h3>
<p>This section provides an overview of the data preparation process, encompassing four sub-sections: HTML scraping from TOPOSText, creation of a filtered dataset of “India-related text,” completeness check and preprocessing of textual data. The tools and procedures employed in data collection and dataset generation for the study are introduced in the subsequent content.</p>
<section id="html-scraping-from-topostext" class="level4" data-number="3.2.1">
<h4 data-number="3.2.1" class="anchored" data-anchor-id="html-scraping-from-topostext"><span class="header-section-number">3.2.1</span> HTML scraping from TOPOSText</h4>
<p>As previously stated, the textual contents of Pliny’s <em>Natural History</em> are available on the <a href="https://topostext.org/the-project">TOPOSText project</a>, presented in two distinct parts: <a href="https://topostext.org/work/148">Book 1-11</a>, <a href="https://topostext.org/work/153">Book 12-37</a>. Both parts are provided in HTML format, offering separate sections of the complete work.</p>
<p>To extract the relevant data, the <a href="https://www.crummy.com/software/BeautifulSoup/bs4/doc/">Beautiful Soup</a> tool, a Python library renowned for parsing HTML and XML documents, was employed.</p>
<p>The text in the HTML documents is organised into paragraphs, each uniquely identified by an “id” attribute that specifies its corresponding book, chapter, and paragraph number. For instance, a typical paragraph has an “id” tag as follows:</p>
<p><strong>&lt;p id=‘urn:cts:latinLit:phi0978.phi001:3.9.7’&gt;</strong></p>
<p>The textual contents are retrieved with the information from these “id” attributes and structured as a reference dataset, comprising the plain text of <em>Natural History</em> divided into paragraphs, with each paragraph assigned a unique identifier, and separate columns indicating its affiliated book, chapter, and paragraph number. An illustrative example of the dataset’s structure is shown as <a href="#tbl-dataset_plaintext">Table&nbsp;3</a>.</p>
<div class="cell" data-df-print="tibble" data-execution_count="3">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<div id="tbl-dataset_plaintext" class="anchored">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Table&nbsp;3: Example for the reference dataset containing the plain text in paragraphs of <em>Natural History</em></caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">UUID4</th>
<th data-quarto-table-cell-role="th">Reference</th>
<th data-quarto-table-cell-role="th">Book</th>
<th data-quarto-table-cell-role="th">Chapter</th>
<th data-quarto-table-cell-role="th">Paragraph</th>
<th data-quarto-table-cell-role="th">Text</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>e9e67565-bb...</td>
<td>urn:cts:lat...</td>
<td>1</td>
<td>1</td>
<td>1.0</td>
<td>PREFACE IN ...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>010b853d-b8...</td>
<td>urn:cts:lat...</td>
<td>1</td>
<td>2</td>
<td>1.0</td>
<td>But who cou...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2d10e332-9c...</td>
<td>urn:cts:lat...</td>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>But if Luci...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>113e0b4c-5b...</td>
<td>urn:cts:lat...</td>
<td>1</td>
<td>4</td>
<td>1.0</td>
<td>My own pres...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>19115032-9f...</td>
<td>urn:cts:lat...</td>
<td>1</td>
<td>5</td>
<td>1.0</td>
<td>For my own ...</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</div>
<div class="cell" data-execution_count="41">
<div class="cell-output cell-output-display">
<p>There are a total of 3493 paragraphs in the English-translated version of <em>Natural History</em> used in this study. The extracted text contains 343096 tokens and 28606 types after preprocessing. This reference dataset has been saved in CSV format for record.</p>
</div>
</div>
<p>Moreover, the geographical annotations concerning the ancient places mentioned in the text are labelled with a class attribute denoted as “place”, including a URI for the location, the place name and its corresponding coordinates, exemplified by the following HTML code snippet:</p>
<p><strong>&lt;a about=“https://topostext.org/place/419125LPal” class=“place” lat=“41.8896” long=“12.4884”&gt;Palatine&lt;/a&gt;</strong></p>
<p>All annotations under the “place” class are extracted, and the URI, name, geographical coordinates, textual content and the book/chapter/paragraph number of each place are structured into the dataset for geographical-related text in <em>Natural History</em>. An example of this dataset is shown in <a href="#tbl-dataset_geotext">Table&nbsp;4</a> for reference.</p>
<div class="cell" data-df-print="tibble" data-fontsize="8pt" data-execution_count="21">
<div class="cell-output cell-output-display" data-execution_count="21">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<div id="tbl-dataset_geotext" class="anchored">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Table&nbsp;4: Example for the <em>Natural History</em> geographical-related text dataset</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">UUID4</th>
<th data-quarto-table-cell-role="th">ToposText_ID</th>
<th data-quarto-table-cell-role="th">Place_Name</th>
<th data-quarto-table-cell-role="th">Reference</th>
<th data-quarto-table-cell-role="th">Lat</th>
<th data-quarto-table-cell-role="th">Long</th>
<th data-quarto-table-cell-role="th">Book</th>
<th data-quarto-table-cell-role="th">Chapter</th>
<th data-quarto-table-cell-role="th">Paragraph</th>
<th data-quarto-table-cell-role="th">Text</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>bf12...</td>
<td>http...</td>
<td>Academy</td>
<td>urn:...</td>
<td>37.9920</td>
<td>23.7070</td>
<td>1</td>
<td>8</td>
<td>1.0</td>
<td>For ...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>f782...</td>
<td>http...</td>
<td>Pala...</td>
<td>urn:...</td>
<td>41.8896</td>
<td>12.4884</td>
<td>2</td>
<td>5</td>
<td>1.0</td>
<td>For ...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>a0f9...</td>
<td>http...</td>
<td>Esqu...</td>
<td>urn:...</td>
<td>41.8950</td>
<td>12.4960</td>
<td>2</td>
<td>5</td>
<td>1.0</td>
<td>For ...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>b8d8...</td>
<td>http...</td>
<td>Capitol</td>
<td>urn:...</td>
<td>41.8933</td>
<td>12.4830</td>
<td>2</td>
<td>5</td>
<td>1.0</td>
<td>For ...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>f81b...</td>
<td>http...</td>
<td>Rome</td>
<td>urn:...</td>
<td>41.8910</td>
<td>12.4860</td>
<td>2</td>
<td>6</td>
<td>3.0</td>
<td>Belo...</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</div>
<div class="cell" data-execution_count="42">
<div class="cell-output cell-output-display">
<p>According to the geographical annotations of the ancient places occurred in <em>Natural History</em>, there are 5595 occurrences of place names in book 1-11 and 3281 in book 12-37, adding up to a combined total of 8876 annotated places throughout the work. The geographical-related text in <em>Natural History</em> contains 199507 tokens and 23937 types after preprocessing. This dataset including place names and their textual context in <em>Natural History</em> is saved in CSV format for record.</p>
</div>
</div>
</section>
<section id="filtered-dataset-of-india-related-text" class="level4" data-number="3.2.2">
<h4 data-number="3.2.2" class="anchored" data-anchor-id="filtered-dataset-of-india-related-text"><span class="header-section-number">3.2.2</span> Filtered dataset of “India-related text”</h4>
<p>As outlined in the Research Question chapter (<a href="#sec-research_question">Section&nbsp;2</a>), this thesis examines texts concerning the Indian region in Pliny’s <em>Natural History</em> as a case study. The objective is to explore how India is described, portrayed, and imagined within this extensive work, providing valuable insights into its complexity.</p>
<p>To ensure a comprehensive contextual analysis, the dataset creation considers not only instances where the word “India” is directly mentioned but also text related to the Indian region. This broader approach aims to encompass a wider scope of relevant information. Drawing from the research and mapping of the Indian region in the perception of the ancient Greek and Roman world, as explained and manifested in the <em>Barrington Atlas of the Greek and Roman World</em> <span class="citation" data-cites="talbert2000-1 talbert2000">(<a href="#ref-talbert2000-1" role="doc-biblioref">Talbert 2000a</a>, <a href="#ref-talbert2000" role="doc-biblioref">2000b</a>)</span>, the approximate coordinates defining the target region are as follows<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>:</p>
<ul>
<li>Latitude: 5-35 degrees North</li>
<li>Longitude: 65-95 degrees East</li>
</ul>
<p>Utilizing the aforementioned dataset of geographical-related text in <em>Natural History</em>, the records with corresponding coordinates falling within the specified range are extracted to construct a dataset relevant to the discourse about the Indian region in the work. The filtering process ensures not only the text explicitly mentioning “India” but also those including other place names situated within the defined boundaries of the Indian region were retained.</p>
<p>The new dataset comprises the textual content and the geographical coordinates of the mentioned Indian place in <em>Natural History</em>. An example of the structure of the dataset of India-related text is shown as <a href="#tbl-dataset_indiatext">Table&nbsp;5</a>.</p>
<div class="cell" data-df-print="tibble" data-fontsize="8pt" data-execution_count="5">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<div id="tbl-dataset_indiatext" class="anchored">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Table&nbsp;5: Example for the India-related dataset</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">UUID4</th>
<th data-quarto-table-cell-role="th">ToposText_ID</th>
<th data-quarto-table-cell-role="th">Place_Name</th>
<th data-quarto-table-cell-role="th">Reference</th>
<th data-quarto-table-cell-role="th">Lat</th>
<th data-quarto-table-cell-role="th">Long</th>
<th data-quarto-table-cell-role="th">Book</th>
<th data-quarto-table-cell-role="th">Chapter</th>
<th data-quarto-table-cell-role="th">Paragraph</th>
<th data-quarto-table-cell-role="th">Text</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">85</td>
<td>fd43dc48-2410-4edd-8131-ce6cc6a3c809</td>
<td>https://topostext.org/place/300740RInd</td>
<td>India</td>
<td>urn:cts:latinLit:phi0978.phi001:2.75.1</td>
<td>30.0000</td>
<td>74.0000</td>
<td>2</td>
<td>75</td>
<td>1.0</td>
<td>Similarly it is reported that at the town of S...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">92</td>
<td>30fe041c-3577-4375-a1f9-a7cc8c9212dc</td>
<td>https://topostext.org/place/300740RInd</td>
<td>India</td>
<td>urn:cts:latinLit:phi0978.phi001:2.75.1</td>
<td>30.0000</td>
<td>74.0000</td>
<td>2</td>
<td>75</td>
<td>1.0</td>
<td>Similarly it is reported that at the town of S...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">93</td>
<td>0d786fbe-aed1-4f9a-9fbf-fa7c228a57cb</td>
<td>https://topostext.org/place/300740RInd</td>
<td>India</td>
<td>urn:cts:latinLit:phi0978.phi001:2.75.1</td>
<td>30.0000</td>
<td>74.0000</td>
<td>2</td>
<td>75</td>
<td>1.0</td>
<td>Similarly it is reported that at the town of S...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">218</td>
<td>b28b62fc-8505-4fa9-aace-bd7b3df792c8</td>
<td>https://topostext.org/place/254683WInd</td>
<td>Indus</td>
<td>urn:cts:latinLit:phi0978.phi001:2.98.1</td>
<td>25.4487</td>
<td>68.3192</td>
<td>2</td>
<td>98</td>
<td>1.0</td>
<td>Near the town of Harpasa in Asia stands a jagg...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">343</td>
<td>b010b6b5-0608-4c97-a980-171813b8b06a</td>
<td>https://topostext.org/place/300740RInd</td>
<td>India</td>
<td>urn:cts:latinLit:phi0978.phi001:2.112.1</td>
<td>30.0000</td>
<td>74.0000</td>
<td>2</td>
<td>112</td>
<td>1.0</td>
<td>Our own portion of the earth, which is my subj...</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</div>
<div class="cell" data-execution_count="40">
<div class="cell-output cell-output-display">
<p>There are 229 occurrences of paragraphs mentioning the places in Indian region with geographical annotation. And the distinct places mentioned are [‘India’ ‘Indus’ ‘Ganges’ ‘Acesinus’ ‘Hydaspes’ ‘Taprobane’ ‘Arachosia’ ‘Muziris’ ‘Baragaza’ ‘Ceylon’]. The textual content about the Indian region compiles 18029 tokens and 5384 types after preprocessing. The dataset for India-related text in <em>Natural History</em> are saved respectively in CSV format for further reference.</p>
</div>
</div>
</section>
<section id="data-completeness-check" class="level4" data-number="3.2.3">
<h4 data-number="3.2.3" class="anchored" data-anchor-id="data-completeness-check"><span class="header-section-number">3.2.3</span> Data completeness check</h4>
<p>The paragraphs extracted from the India-related text dataset undergo manual verification for the completeness of Indian place name annotations. Each distinct paragraph in the dataset is individually extracted and stored in TXT format as separate files within a corpus folder. The file names contain information about the affiliating book, chapter, and paragraph numbers.</p>
<div class="cell" data-execution_count="44">
<div class="cell-output cell-output-display">
<p>There are in total 146 distinct paragraphs mentioning Indian places in <em>Natural History</em> according to the annotations on TOPOSText.</p>
</div>
</div>
<p>An example of the exported file name can be referred as follows:</p>
<div class="cell" data-execution_count="34">
<div class="cell-output cell-output-stdout">
<pre><code>Exported india_corpus\37.77.1_text.txt</code></pre>
</div>
</div>
<p>The text files are uploaded to <a href="https://recogito.pelagios.org/">Recogito</a> platform, which offers a semantic annotation tool and automatic geographical annotation suggestions from its supported gazetteers. This process aims to find Indian place names mentioned in the target corpus that were not annotated in TOPOSText. These unidentified place names are then marked on the <a href="https://recogito.pelagios.org/">Recogito</a> workspace with the available geographical coordinates information as additional annotations. And the identified annotations are exported in CSV format for a supplement to the dataset of India-related text in <em>Natural History</em>.</p>
<p>As shown in <a href="#tbl-supplement_annotation">Table&nbsp;6</a>, the supplement annotations are organized in the following manner:</p>
<p><strong>FILE</strong>: This column contains the name of the file indicating the book, chapter, and paragraph number where the mentioned place name appears.</p>
<p><strong>QUOTE_TRANSCRIPTION</strong>: This column contains the textual name of the place as mentioned in the text.</p>
<p><strong>URI</strong>: The URI column contains the unique identifier for the place obtained from the gazetteers available on the <a href="https://recogito.pelagios.org/">Recogito</a> platform.</p>
<p><strong>VOCAB_LABEL</strong>: This column contains the confirmed automatically matched geographical name with the corresponding place name mentioned in the text.</p>
<p><strong>LAT&amp;LNG</strong>: The LAT and LNG columns contain the corresponding coordinates (latitude and longitude) associated with the place. Note that some places identified may not have matching coordinates.</p>
<p><strong>PLACE_TYPE</strong>: This column contains the automatically matched geographical role provided by the gazetteers. It describes the type of the place.</p>
<p><strong>VERIFICATION_STATUS</strong>: This column indicates whether the place names have been “verified” with confirmed coordinates that match the gazetteers’ information.</p>
<p><strong>COMMENTS</strong>: This column includes manual remarks for the place names that do not have matching coordinates but are believed to indicate Indian place names based on the context.</p>
<div class="cell" data-execution_count="46">
<div class="cell-output cell-output-display" data-execution_count="46">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<div id="tbl-supplement_annotation" class="anchored">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1" data-tbl-colwidths="[5,5,5,10,10,5,5,5,5,45]">
<caption>Table&nbsp;6: Example for supplement annotation to Indian places in <em>Natural History</em></caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">FILE</th>
<th data-quarto-table-cell-role="th">QUOTE_TRANSCRIPTION</th>
<th data-quarto-table-cell-role="th">TYPE</th>
<th data-quarto-table-cell-role="th">URI</th>
<th data-quarto-table-cell-role="th">VOCAB_LABEL</th>
<th data-quarto-table-cell-role="th">LAT</th>
<th data-quarto-table-cell-role="th">LNG</th>
<th data-quarto-table-cell-role="th">PLACE_TYPE</th>
<th data-quarto-table-cell-role="th">VERIFICATION_STATUS</th>
<th data-quarto-table-cell-role="th">COMMENTS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2.75.1_text.txt</td>
<td>hypasis</td>
<td>PLACE</td>
<td>http://pleiades.stoa.org/places/60110</td>
<td>Zadadros/Hypasis/Sydrus (river)</td>
<td>32.500000</td>
<td>72.500000</td>
<td>river</td>
<td>VERIFIED</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>6.21.4_text.txt</td>
<td>sydrus</td>
<td>PLACE</td>
<td>http://pleiades.stoa.org/places/60110</td>
<td>Zadadros/Hypasis/Sydrus (river)</td>
<td>32.500000</td>
<td>72.500000</td>
<td>river</td>
<td>VERIFIED</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>6.21.4_text.txt</td>
<td>rhodapha</td>
<td>PLACE</td>
<td>http://pleiades.stoa.org/places/60019</td>
<td>Rhodopha</td>
<td>27.500000</td>
<td>77.500000</td>
<td>unknown</td>
<td>VERIFIED</td>
<td>A river in India, mentioned by Pliny\nhttps://...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>6.21.4_text.txt</td>
<td>palibothra</td>
<td>PLACE</td>
<td>http://pleiades.stoa.org/places/59978</td>
<td>Palibothra|Palibothra, Patna Skt.: Paṭaliputra</td>
<td>25.614443</td>
<td>85.135020</td>
<td>settlement</td>
<td>VERIFIED</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>6.21.5_text.txt</td>
<td>prinas</td>
<td>PLACE</td>
<td>http://pleiades.stoa.org/places/60008</td>
<td>Prinas (river)</td>
<td>25.621435</td>
<td>86.511556</td>
<td>river</td>
<td>VERIFIED</td>
<td>NaN</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</div>
<div class="cell" data-execution_count="194">
<div class="cell-output cell-output-display" data-execution_count="194">
<pre><code>PLACE_TYPE
river                   14
settlement              13
island                   6
unknown                  4
cape                     3
mountain                 2
people                   2
lake                     1
unlocated                1
unlocated,river          1
unlocated,settlement     1
Name: UUID, dtype: int64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="48">
<div class="cell-output cell-output-display">
<p>After the manual annotation check, 56 Indian place names were identified and added as supplementary annotations to the existing dataset, most of which are names of rivers, settlements, and islands. Among these, 45 place names have confirmed corresponding coordinates based on the reference in Recogito. For the other 11 place names, though have no matching coordinates on Recogito, there are contextual clues indicating that they are probably Indian location names.</p>
</div>
</div>
<div class="cell" data-execution_count="50">
<div class="cell-output cell-output-display">
<p>The supplemented place name annotations were added to the India-related text dataset. The updated dataset contains 285 occurrences of paragraphs mentioning Indian places. And the distinct place names mentioned are [‘India’ ‘Indus’ ‘Ganges’ ‘Acesinus’ ‘Hydaspes’ ‘Taprobane’ ‘Arachosia’ ‘Muziris’ ‘Baragaza’ ‘Ceylon’ ‘Hypasis’ ‘Sydrus’ ‘Rhodapha’ ‘Palibothra’ ‘Prinas’ ‘Cainas’ ‘Condochates’ ‘Erannoboas’ ‘Cosoagus’ ‘Sonus’ ‘Protalis’ ‘Peucolaitis’ ‘Taxilla’ ‘Modogalinga’ ‘Andarae’ ‘Dardae’ ‘Methora’ ‘Chrysobora’ ‘Dandaguda’ ‘Tropina’ ‘Patala’ ‘Capitalia’ ‘Automula’ ‘Amenda’ ‘Cantaba’ ‘Prasiane’ ‘Argyre’ ‘Crocala’ ‘Bibraga’ ‘Toralliba’ ‘Hippuros’ ‘Palaesimundus’ ‘Megisba’ ‘Palesimundus’ ‘Cydara’ ‘Coliacum’ ‘Emodian mountains’ ‘Capisa’ ‘Parabeste’ ‘Cartana’ ‘Tonberos’ ‘Arosapes’ ‘Gedrusi’ ‘Arbis’ ‘Sigerus’ ‘Catarcludi’ ‘Meros’ ‘Perimula’ ‘Chenab’ ‘Oratae’].</p>
</div>
</div>
<div class="cell" data-execution_count="52">
<div class="cell-output cell-output-display">
<p>And the supplemented Indian place names are updated to the dataset of geographically-related text, which contains all place name occurrences in <em>Natural History</em>. The supplement expanded the dataset from 8876 occurrences of geographical names to 8932.</p>
</div>
</div>
</section>
<section id="preprocessing-of-texts" class="level4" data-number="3.2.4">
<h4 data-number="3.2.4" class="anchored" data-anchor-id="preprocessing-of-texts"><span class="header-section-number">3.2.4</span> Preprocessing of texts</h4>
<p>The textual contents stored in the “Text” column of the mentioned datasets are utilized as corpora for different analyses with three distinct scales: the text of the entire work, the text specifically related to geographical content, and the text related to Indian content. To prepare the data for analysis, a preprocessing process is applied using a defined function, which employs tools from the <a href="https://www.nltk.org/">NLTK</a> package.</p>
<p>During the preprocessing, the texts are tokenized, preserving punctuation marks, and lemmatized to their base forms. Furthermore, common English stopwords are excluded from the corpus, considering the text applied for this study is an English-translated version. To reduce the noise of short strings, tokens with lengths lower than two will not be appended to the output token list. The output of this preprocessing is a refined corpus presented as a nested list structure, with paragraphs forming the smallest nesting unit.</p>
<p>The extensions computed for each corpus mentioned earlier are based on this preprocessing procedure. The preprocessing steps helps optimally organise the corpora, ensuring that they are conducive to meaningful analyses and facilitating the extraction of valuable insights from the text at varying scales.</p>
</section>
</section>
</section>
<section id="data-analysis" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="data-analysis"><span class="header-section-number">4</span> Data Analysis</h2>
<section id="place-name-distribution-in-india-related-text" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="place-name-distribution-in-india-related-text"><span class="header-section-number">4.1</span> Place name distribution in India-related text</h3>
<p>The comparison between the total number of place names and the place names specifically related to the Indian subcontinent mentioned in each book, is depicted in <a href="#fig-grouped_place_name_count_comparison">Figure&nbsp;3</a>. The difference in numbers between the two categories is significant, as indicated by the large disparity.</p>
<p>To facilitate a more effective comparison of the referencing trends across different books, <a href="#fig-subplots_place_name_count_comparison">Figure&nbsp;4</a> presents subplots with varying y-axis scales. This approach allows for a clearer visualization of the trends and patterns in place name references throughout the various books.</p>
<div class="cell" data-execution_count="29">
<div class="cell-output cell-output-display">
<div id="fig-grouped_place_name_count_comparison" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;3: Occurence count for all place names and place names of Indian subcontinent in each book</figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-grouped_place_name_count_comparison-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-execution_count="30">
<div class="cell-output cell-output-display">
<div id="fig-subplots_place_name_count_comparison" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;4: Occurence count for all place names and place names of Indian subcontinent in each book_different y-axis scales</figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-subplots_place_name_count_comparison-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The figures reveal a distinct difference between the occurrence trends of place names related to the Indian subcontinent and all place names collectively. Specifically, the referencing of the Indian subcontinent is highly concentrated in books 6, 12, and 37 of Pliny’s narrative. This discrepancy indicates that the mentioning of place names from the Indian subcontinent is closely tied to specific themes and topics within Pliny’s work.</p>
<p>In this regard, three methodologies have been employed to analyze the texts pertaining to the Indian subcontinent in <em>Natural History</em>, including word frequency and collocation analysis, topic modeling, and network analysis. The objective of these analyses is to delve deeper into the textual content, unraveling the intricate relationships and uncovering the underlying themes and connections associated with the place names of the Indian subcontinent.</p>
<p>Through word frequency and collocation analysis, the aim is to identify keyword and significant word combinations co-occur in the textual content about India in <em>Natural History</em>. This analysis provides insights into the specific linguistic patterns and contextual associations surrounding the Indian places mentioned in the work, providing an overview of the keyword in the discourse.</p>
<p>Topic modeling allows for a broader exploration of the thematic landscape within which the Indian subcontinent place names are embedded. By clustering related words and identifying prevalent topics, this methodology helps to discern the major themes and subject matters that emerge from Pliny’s narrative, providing a comprehensive understanding of the broader context in which these place names are mentioned.</p>
<p>Furthermore, network analysis offers a visual representation of the interconnections among the place names of the Indian subcontinent and other entities in Pliny’s work. By examining the relationships between different locations and named entities, this analysis uncovers the geographical and conceptual networks that exist within the text, revealing how the Indian subcontinent place names contribute to the overall structure and narrative flow of <em>Natural History</em>.</p>
<p>Together, these methodologies aim to provide a nuanced and comprehensive exploration of the texts related to the Indian subcontinent in <em>Natural History</em>. By delving into the linguistic, thematic, and network aspects of these place names, a deeper understanding of their role in shaping Pliny’s narrative can be achieved.</p>
</section>
<section id="word-frequency-and-collocating-bi-grams" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="word-frequency-and-collocating-bi-grams"><span class="header-section-number">4.2</span> Word frequency and collocating bi-grams</h3>
<p>By utilizing the measurements available in the <a href="https://www.nltk.org/">NLTK</a> package, a word frequency list and collocating bi-grams were generated from the text associated with Indian place names in <em>Natural History</em>. These outputs provide an overview of the prevalent words and word patterns, as potential keywords in the text.</p>
<p>In the initial observation, the words “India” and “one” ranked high in the frequency list. However, it is apparent that the passages would include the word “India” when discussing about India, making it less informative as a keyword. Likewise, the word “one” appeared as a generic descriptor for bringing up a type of tribe, plant, or attributes like distance, volume, or range, offering limited insight as a keyword. To enhance the relevance and descriptive nature of the frequency list, these two common but less informative words, “India” and “one”, are further excluded from the token list.</p>
<div class="cell" data-execution_count="18">
<div class="cell-output cell-output-display">
<p>Among 17729 tokens excluding “India” and “one”, 201 (the top 1%) frequently occuring words in the India-related text in <em>Natural History</em> are shown in <a href="#fig-freqwords_treemap">Figure&nbsp;5</a> and <a href="#fig-freqwords_wordcloud">Figure&nbsp;6</a>.</p>
</div>
</div>
<div class="cell" data-execution_count="19">
<div class="cell-output cell-output-display">
<div id="fig-freqwords_treemap" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;5: Top 1% frequent words in Indian subcontinent related text as tree map</figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-freqwords_treemap-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-execution_count="20">
<div class="cell-output cell-output-display">
<div id="fig-freqwords_wordcloud" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;6: Top 1% frequent words in Indian subcontinent related text as word cloud</figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-freqwords_wordcloud-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>An intriguing observation from the word frequency sorting is the prominence of the word “also” in the given text. The word “also” appears frequently, which can be attributed to the encyclopaedic nature of the work, where it is often used to draw comparisons in introductions about species and natural phenomena.</p>
<p>As shown in the following examples where “also” appears in the India-related text in <em>Natural History</em>, it is indeed used when comparing the counterparts in India after introducing a natural phenomenon, plant or human activity. In this regard, the common use of “also” may imply that India holds significance as a contrast in the broader narrative.</p>
<blockquote class="blockquote">
<p>2.75.1 “<strong>Also</strong> in India at the well-known port of Patala the sun rises……”</p>
</blockquote>
<blockquote class="blockquote">
<p>12.10.1 “In India there is <strong>also</strong> a thorn the wood of which resembles ebony……”</p>
</blockquote>
<blockquote class="blockquote">
<p>12.15.1 “There is <strong>also</strong> in India a grain resembling that of pepper, but larger and more brittle……”</p>
</blockquote>
<blockquote class="blockquote">
<p>12.17.1 “Arabia <strong>also</strong> produces cane-sugar, but that grown in India is more esteemed.”</p>
</blockquote>
<p>The hypothesis is further confirmed towards the end of the work in book 37, where Pliny concludes his comprehensive discourse on “Nature”. In 37.77.1, Pliny bestows the highest praise upon Italy, considering it to have earned “Nature’s crown”. And in this context, when expressing his preference and overall judgment, Pliny makes one final mention of “India”. He indicates that, “if we leave aside the fabulous marvels of India”<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>, Spain can be appreciated as a significant and attractive destination, second only to Italy. This unintentional highlight of India suggests that it holds considerable importance as a distant contrast to the Mediterranean area, where the focal point locates in the <em>Natural History</em>’s world scope.</p>
<p>And following by “also”, the words “stone”, “river”, “called” and “colour” notably stand out in the word frequeny sorting. These frequent occurrences suggest some potential themes related to India in the content of <em>Natural History</em>, which aligns with the distribution of Indian place names as depicted in <a href="#fig-subplots_place_name_count_comparison">Figure&nbsp;4</a>.</p>
<p>Looking into the text in the three books pertaining the most mentions of Indian place names, book 6 includes specific topics on Nations of India, the Ganges and Indus (two main rivers in India) and routes of voyages to India, and book 12 contains introductions to trees and the economic values of their roots and leaves, as well as plants and their medical and flavouring effects. While book 37 focuses on descriptions of different types of gemstones, where the priciple types are introduced in a sequence/category of colours, alongside critics about the luxury trade they represents.</p>
<p>The frequent use of the word “river” in India-related text may be related to the mention of voyage and trading routes concerning India in <em>Natural History</em>. On the other hand, “stone” and “color” clearly connect to the content in book 37, which deals with gemstones.</p>
<p>As indicated by <span class="citation" data-cites="roller2022">Roller (<a href="#ref-roller2022" role="doc-biblioref">2022</a>)</span>, “Rivers, especially, were of significancetotheRomans:Romeoweditsoriginstoitscontrolof a major crossing of the Tiber that affected travel throughout the Italian peninsula, and river cults were a major part of Roman ideology”.</p>
<p>These two potential themes observed from the frequent occuring words indicate that the geographical location and routes toward Indian subcontinent, and its role as an origin of many plants, animals and gemstones, pocesses a significance in the content about India in <em>Natural History</em>.</p>
<p>In addition to word frequency observation, collocation analysis is utilized to explore the common word patterns within the India-related text in <em>Natural History</em>.</p>
<div class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<p>The top 0.1% of the most likely collocating bi-grams are extracted using the likelihood ratio measurement. This selection process yields 18 out of 17728 bi-grams that are most significant and likely to co-occur together in the target corpus.</p>
</div>
</div>
<p>However, during the initial observation, it was noted that approximately one-third of the extracted bi-grams contained the word “hundred”, such as in (‘hundred’, ‘fifty’) and (‘six’, ‘hundred’). These bi-grams typically denoted measurements for distance, object length, or quantity, offering limited descriptive information about the content of the text. Consequently, the word “hundred” was excluded from further bi-gram extraction to focus on more informative and relevant co-occuring words.</p>
<p>And the updated output bi-grams are list as follows:</p>
<div class="cell" data-execution_count="21">
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>[('alexander', 'great'),
 ('father', 'liber'),
 ('caspian', 'gate'),
 ('fifty', 'mile'),
 ('denarii', 'pound'),
 ('gold', 'silver'),
 ('precious', 'stone'),
 ('river', 'indus'),
 ('fourteen', 'equinoctial'),
 ('olive', 'oil'),
 ('asia', 'minor'),
 ('equinoctial', 'hour'),
 ('lapis', 'lazuli'),
 ('red', 'sea'),
 ('mile', 'breadth'),
 ('emperor', 'nero'),
 ('already', 'mentioned'),
 ('ft.', 'long')]</code></pre>
</div>
</div>
<p>The extracted bi-grams can be broadly categorized into four types:</p>
<p><strong>Historical figures</strong>: (‘alexander’, ‘great’), (‘father’, ‘liber’), (‘emperor’, ‘nero’)</p>
<p><strong>Geographical locations and features</strong>: (‘caspian’, ‘gate’), (‘river’, ‘indus’), (‘asia’, ‘minor’), (‘red’, ‘sea’)</p>
<p><strong>Meseuarments (distance, currency, length, time)</strong>: (‘fifty’, ‘mile’), (‘denarii’, ‘pound’), (‘fourteen’, ‘equinoctial’), (‘equinoctial’, ‘hour’), (‘mile’, ‘breadth’), (‘ft.’, ‘long’)</p>
<p><strong>Trading goods</strong>: (‘gold’, ‘silver’), (‘precious’, ‘stone’), (‘olive’, ‘oil’), (‘lapis’, ‘lazuli’)</p>
<p>On the one hand, the presence of bi-grams associated with geographical locations, distance, and time measurements in the India-related text reaffirms India’s position as a geographic reference, consistent with the earlier findings from the word frequency list and literature review. On the other hand, within the context of the Indo-Mediterranean network of exchange, the occurrence of bi-grams related to geographical locations, currency measurements, and trading goods underscores the importance of India’s role in merchandise trade within the narratives of <em>Natural History</em>.</p>
<p>Furthermore, the occurrence of historical figures such as “Alexander III, the Great (king of Macedon)”, “Nero (Roman emperor)”, and “Father Liber (referring to Dionysus, the Greek god of winemaking and wine)” suggests their connections with India in the history of expeditions or mythical tales (Dionysus is believed to have conquered India in Greek epic). This observation opens up a perspective for clustering the human names mentioned in the text to reveal the content structure about India in <em>Natural History</em>, which will be further explored in the Network Analysis section.</p>
<p>In conclusion, the analysis of word frequency and collocation in the India-related text within <em>Natural History</em> reveals noteworthy word patterns. These patterns suggest that India holds a significant role as a geographical contrast, being compared in terms of distance, natural phenomena, and origin of products with other regions introduced in the narrative. Furthermore, it is highlighted for its prominent role in merchandise trade in the portrait of India in <em>Natural History</em>.</p>
</section>
<section id="topic-modeling" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="topic-modeling"><span class="header-section-number">4.3</span> Topic modeling</h3>
<p>Furthermore, topic modeling approach is applied to delve further into the underlying topics about India in the work. Topic modeling is a widely used method for text analysis that infers the latent topics in a collection of documents<span class="citation" data-cites="bail underwood2012">(<a href="#ref-bail" role="doc-biblioref">Bail n.d.</a>; <a href="#ref-underwood2012" role="doc-biblioref">Underwood 2012</a>)</span>. Latent Dirichlet Allocation (LDA), as its most commonly employed algorithm, operates under an assumption that each document contains a mixture of different topics, and each topic is defined as a collection of words with varying probabilities of appearance in the passages<span class="citation" data-cites="underwood2012 kapadia2022">(<a href="#ref-underwood2012" role="doc-biblioref">Underwood 2012</a>; <a href="#ref-kapadia2022" role="doc-biblioref">Kapadia 2022</a>)</span>.</p>
<p>In this study, the collection of India-related text in <em>Natural History</em>, segmented into paragraphs, are considered as different “documents”. And the <a href="https://radimrehurek.com/gensim/">Genism</a> library in Python is utilized for semantic vectorization and the implementation of the LDA model on the groups of words within the text<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p>
<p>Since the corpus size for text pertaining to Indian place names is relatively small, after several attempts with a consideration of the coherence score distribution depicted in <a href="#fig-topic_coherence_distribution">Figure&nbsp;7</a>, the number of topics is determined to be 3, with 40 passes to obtain the most optimal and non-overlapping topic clusters.</p>
<div class="cell" data-execution_count="75">
<div class="cell-output cell-output-display">
<div id="fig-topic_coherence_distribution" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;7: Conherence distribution of different topic numbers when passes=40</figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-topic_coherence_distribution-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>And the list of 30 keywords, grouped by the 3 assigned topics, is presented below.</p>
<div class="cell" data-execution_count="27">
<div class="cell-output cell-output-stdout">
<pre><code>[(0,
  '0.014*"stone" + 0.011*"also" + 0.007*"colour" + 0.007*"india" + '
  '0.007*"found" + 0.006*"like" + 0.004*"one" + 0.004*"black" + 0.004*"tree" + '
  '0.004*"amber" + 0.004*"name" + 0.003*"known" + 0.003*"white" + 0.003*"kind" '
  '+ 0.003*"gold" + 0.003*"made" + 0.003*"even" + 0.003*"called" + '
  '0.003*"indian" + 0.003*"glass" + 0.002*"part" + 0.002*"people" + '
  '0.002*"used" + 0.002*"variety" + 0.002*"many" + 0.002*"river" + '
  '0.002*"make" + 0.002*"rock-crystal" + 0.002*"island" + 0.002*"red"'),
 (1,
  '0.009*"stone" + 0.008*"also" + 0.007*"india" + 0.006*"like" + 0.006*"kind" '
  '+ 0.006*"colour" + 0.005*"name" + 0.005*"one" + 0.004*"called" + '
  '0.004*"even" + 0.004*"white" + 0.003*"pepper" + 0.003*"variety" + '
  '0.003*"another" + 0.003*"known" + 0.003*"tree" + 0.003*"black" + '
  '0.003*"weight" + 0.003*"leaf" + 0.003*"purple" + 0.002*"grain" + '
  '0.002*"people" + 0.002*"denarii" + 0.002*"used" + 0.002*"nard" + '
  '0.002*"resembles" + 0.002*"pound" + 0.002*"taste" + 0.002*"found" + '
  '0.002*"small"'),
 (2,
  '0.011*"river" + 0.010*"hundred" + 0.008*"one" + 0.007*"india" + '
  '0.007*"also" + 0.007*"city" + 0.007*"mile" + 0.007*"sea" + 0.006*"island" + '
  '0.005*"nation" + 0.005*"called" + 0.005*"people" + 0.004*"day" + '
  '0.004*"come" + 0.004*"two" + 0.004*"distance" + 0.004*"name" + '
  '0.004*"place" + 0.004*"salt" + 0.004*"king" + 0.003*"elephant" + '
  '0.003*"water" + 0.003*"country" + 0.003*"foot" + 0.003*"alexander" + '
  '0.003*"thousand" + 0.003*"upon" + 0.003*"mountain" + 0.003*"even" + '
  '0.003*"part"')]</code></pre>
</div>
</div>
<p>Based on the prominent categories of the keywords and the possible interconnection within each group, a interpretation of the topic emerged from each keyword clusters can be drawn as follows.</p>
<p><strong>Group 0</strong>: This group consists of keywords related to precious stones, such as “stone”, “amber”, “rock-crystal”and “glass”, with colour references like “black”, “white”, and “red”. Therefore, the underlying topic appears to be the description of precious stones.</p>
<p><strong>Group 1</strong>: This group comprises various natural products, such as “tree”, “leaf”, “pepper”,“grain” and “nard”, along with descriptive words like “weight”, “pound” and “taste”. In addition, the ancient Roman currency “denarii” appears in the group, suggesting a possible topic related to merchandise trade with Indian subcontinent.</p>
<p><strong>Group 2</strong>: This group contains different geographical features, such as “river”, “island”, “sea” and “mountain”. It also includes terms related to cities, nations, kings, and distances, and the name “Alexander”, referring to Alexander the Great, who has undertook an expedition to Indian subcontinent. “Elephant”, as an important property of the King in India during Pliny’s era, also represents the power and size of the Indian kingdoms. In this regard, the underlying topic for this group likely pertains to geography and society in India.</p>
<p>The interactive visualisation of the 3 topic clusters, manifesting the intertopic distance map and the most salient/relevant terms within the given textand their contributing weights for each topic, can be accessed on the html version of this <a href="https://raw.githack.com/lizaodawn/NH_thesis/main/NHthesis_structure.html">thesis</a>.</p>
<p>The static demonstration of the visualisation can be referred in <a href="#fig-topic_cluster0">Figure&nbsp;8</a>, <a href="#fig-topic_cluster1">Figure&nbsp;9</a>, <a href="#fig-topic_cluster2">Figure&nbsp;10</a> and <a href="#fig-topic_cluster3">Figure&nbsp;11</a>.</p>
<p>The intertopic distance map is shown on the left panel of the interactive chart. Each bubble represents a topic, and the size of the bubble indicates the percentage of the texts in the corpus contributing to the topic. The distance between the bubbles implies the extent of difference between them. And a good topic model is expected to have big and non-overlapping bubbles scattered throughout the chart <span class="citation" data-cites="tran2022">(<a href="#ref-tran2022" role="doc-biblioref">Tran 2022</a>)</span>.</p>
<p>And the most salient/relevant keyword is shown on the right panel. The blue bars represent the overall frequency of each word in the corpus. If no topic is selected, the blue bars of the most frequently used words will be displayed. The contribution of the frequent word to each topic will be shown in size difference when hovering. And when hovering on the bubbles in the left panel, there will be red bars in the right panel giving the estimated number of times a given term was generated by a given topic. The word with the longest red bar is estimated to be used the most in the texts belonging to that topic.</p>
<div class="cell" data-execution_count="38">
<div class="cell-output cell-output-display" data-execution_count="38">


<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/bmabey/pyLDAvis@3.3.1/pyLDAvis/js/ldavis.v1.0.0.css">


<div id="ldavis_el887629447782910082926906180"></div>
<script type="text/javascript">

var ldavis_el887629447782910082926906180_data = {"mdsDat": {"x": [-0.06020065453157122, -0.05848214240950726, 0.11868279694107844], "y": [0.06711275307387092, -0.06776375140415741, 0.0006509983302864871], "topics": [1, 2, 3], "cluster": [1, 1, 1], "Freq": [38.4072768206273, 17.601294913153765, 43.99142826621893]}, "tinfo": {"Term": ["stone", "hundred", "mile", "city", "colour", "nation", "river", "kind", "like", "amber", "black", "pepper", "thousand", "island", "white", "variety", "found", "glass", "sea", "five", "distance", "weight", "name", "grain", "denarii", "purple", "also", "alexander", "leaf", "india", "amber", "glass", "layer", "sardonyx", "xenocrates", "shed", "pine", "beast", "aloe", "'smaragdi", "writes", "respect", "beryl", "shining", "drop", "graft", "alp", "vermilion", "call", "thoroughly", "magi", "linen", "rock-crystal", "meleager", "exudation", "vinegar", "belief", "washed", "midwinter", "ink", "property", "closely", "story", "sometimes", "amethyst", "stone", "piece", "occurs", "found", "black", "colour", "use", "1/2", "gold", "also", "like", "tree", "white", "live", "made", "india", "gem", "known", "greek", "indian", "kind", "bird", "name", "even", "make", "used", "variety", "one", "according", "called", "part", "many", "people", "red", "river", "island", "pepper", "hound", "millet", "ebony", "bdellium", "mastich", "stalk", "nonius", "peck", "pungency", "triumph", "gingelly", "reign", "pod", "spoken", "denarii", "tuft", "panic", "ginger", "heavier", "adulterate", "master", "'paederos", "juniper", "indigo", "lentisk", "irio", "foreign", "contained", "grain", "nard", "pound", "taste", "weight", "genuine", "kind", "purple", "small", "variety", "leaf", "like", "resembles", "dog", "stone", "colour", "name", "india", "another", "white", "also", "one", "alone", "even", "called", "black", "tree", "known", "used", "price", "people", "red", "found", "nation", "hundred", "thousand", "five", "fifty", "city", "mile", "promontory", "stadium", "opposite", "hour", "navigable", "founded", "twenty", "thence", "twenty-five", "parthia", "dwell", "breadth", "situate", "twelve", "direction", "alexandria", "extent", "fifteen", "thirty", "harbour", "chain", "ichthyophagi", "onesicritus", "desert", "lie", "distance", "town", "indus", "whose", "stated", "ganges", "river", "salt", "territory", "alexander", "sea", "island", "horse", "elephant", "day", "foot", "king", "upon", "writer", "country", "two", "one", "come", "place", "people", "called", "india", "also", "mountain", "water", "name", "great", "part", "even"], "Freq": [129.0, 78.0, 55.0, 57.0, 72.0, 43.0, 100.0, 49.0, 71.0, 26.0, 35.0, 11.0, 26.0, 64.0, 38.0, 30.0, 64.0, 19.0, 65.0, 19.0, 33.0, 15.0, 72.0, 9.0, 8.0, 17.0, 154.0, 30.0, 20.0, 130.0, 25.66987056428824, 18.528896588216536, 8.186453471507791, 6.6163039935536, 5.8222511839623285, 5.822145986367254, 5.822142358863975, 5.759585258715183, 5.028197971315138, 5.028173787959949, 5.027012180799003, 5.003792129257694, 9.795273746633988, 4.234103646964125, 4.233945245987632, 4.2339456490435525, 4.22958418093509, 4.2245060794011735, 12.77629306414462, 4.204792211306451, 8.989941417126323, 10.54659900122018, 13.766160515986478, 3.4400681687774064, 3.4400597046030903, 3.4400593015471705, 3.4400584954353306, 3.4400512404287737, 3.440050837372854, 3.4400496282050943, 7.413434941204599, 7.406723254027619, 8.787430000767788, 12.945408879209861, 6.618021414827989, 97.69044963262346, 9.000249975331851, 11.379256103756687, 46.63464044065819, 26.31722190157184, 50.06799329475533, 8.85914574058284, 6.577685593651171, 22.767547109012245, 74.40396157793755, 39.06137770500487, 25.82208382629956, 23.38341010561518, 12.423239455618374, 22.70577637096304, 49.928532722047386, 11.374874079796314, 23.731626236991648, 10.592756965158918, 20.480538494288222, 22.86175901193659, 11.831707332671792, 25.55559453767484, 22.52395784552849, 14.354422243199572, 15.587389648638515, 15.174415328735073, 27.069922382956488, 13.305515966333102, 22.506529707555114, 16.913040568953818, 14.465657615953788, 16.686247451761144, 13.450873247148143, 14.372217968171832, 13.718396777263145, 10.925287877472826, 4.041130865609856, 4.041119413431641, 4.029585961693732, 3.4029918522582707, 3.401424012118114, 2.764857087295378, 2.764856163732619, 2.764856163732619, 2.764855055457308, 2.764838246615089, 2.7648001958294066, 2.753489692141588, 2.7494712705759534, 2.7450475896715463, 7.0440456744502224, 2.1267151185429634, 2.126712901992341, 2.12670976187896, 2.126708099465993, 2.1267023733768853, 2.126701449814126, 2.12670181923923, 2.126701449814126, 2.12669092119867, 2.1266506538623657, 2.126632367319732, 2.122910039974723, 2.1193600494405964, 7.412409789265017, 6.6227695408808716, 6.292813815248874, 6.283850823382598, 8.501596905294157, 4.0503003661091075, 18.728732661317274, 8.002362469788737, 6.202893528454591, 10.835073528295986, 8.26029655490133, 18.878296631105968, 6.532556669404448, 4.037869580794281, 27.699402658949335, 18.218855088573896, 17.119092809525878, 23.67804342489018, 9.513014126190122, 11.160607235436544, 23.943277350052135, 15.815604407383647, 4.049049123282833, 11.696463520323205, 12.672197231601357, 8.573490724727677, 8.574986157547505, 8.716207769644157, 6.964398360939981, 5.326225961263336, 7.245007020068249, 6.014561718857189, 6.279278079448842, 42.664066110158686, 77.53612261575508, 25.58828209415664, 19.02534866596276, 14.968717539513529, 55.319710844724355, 53.17541908119011, 13.241271063113427, 10.88796204121295, 10.071437737668022, 10.041429079923814, 8.438019804615964, 8.425553206761673, 9.93235327356056, 19.010837848907652, 7.621177880743541, 7.61961794021067, 7.615100622035428, 7.612042603068355, 7.61175545213274, 7.604405865484824, 7.59144667912844, 6.798745285118211, 6.774873439893521, 6.735564231106039, 7.4827651282298415, 5.988075721389169, 5.987907678076365, 5.987923374429759, 6.733059277767372, 16.516980908774467, 17.955542464166214, 29.716269766448942, 19.03109907119432, 19.010516535320534, 16.871408261665856, 18.97883206102281, 16.52043041326148, 83.49869083956443, 28.8811831400435, 13.884417140330177, 25.856246546035788, 51.93942912280917, 50.930371501906215, 13.076182358006983, 27.719372301171806, 35.60931237787287, 25.96454030467407, 28.240044349431344, 25.465745279785853, 22.601971455906327, 26.266794825514314, 31.776724536562245, 59.71923989083979, 32.58668961101838, 29.008126013143414, 36.449270413719816, 41.48468643526481, 57.1812503448527, 56.169777332156904, 24.903821368177624, 26.41662298186237, 29.39080126225419, 21.098299580007332, 22.986820188304687, 24.748213260521027], "Total": [129.0, 78.0, 55.0, 57.0, 72.0, 43.0, 100.0, 49.0, 71.0, 26.0, 35.0, 11.0, 26.0, 64.0, 38.0, 30.0, 64.0, 19.0, 65.0, 19.0, 33.0, 15.0, 72.0, 9.0, 8.0, 17.0, 154.0, 30.0, 20.0, 130.0, 26.15893520709623, 19.65070958079411, 8.689614914606446, 7.101312380005396, 6.307247015725121, 6.307248310690323, 6.307247770149479, 6.308305563935816, 5.5131798530648295, 5.513173217309121, 5.513180315701896, 5.513152373215906, 10.915825679959628, 4.7191020837621664, 4.719104851382407, 4.719107030561662, 4.719117927749737, 4.719176667617408, 14.27499260645074, 4.719703104102346, 10.121585705323294, 11.888381415418255, 15.524434397744926, 3.9250369905739855, 3.9250354174798545, 3.9250352682178034, 3.9250350624837202, 3.925034138779098, 3.925034104621593, 3.925033651721533, 8.533688648985628, 8.533303796210888, 10.305131663305747, 15.543229215491376, 7.739357953332393, 129.93503980392296, 10.7597405335994, 13.784869282463951, 64.69748955646716, 35.234005436209365, 72.69264119776368, 10.755120452436406, 7.736304822936346, 33.08152619461518, 154.5170162601466, 71.18839932045651, 42.59749501045614, 38.6766940680917, 18.012025312284457, 41.59977063246695, 130.78782649179027, 16.331759890675077, 46.700980647743826, 14.796622454557964, 41.33134590041513, 49.64110977975771, 17.67138493094675, 72.0654886094549, 58.96863462637272, 25.744281743617147, 31.089316231506743, 30.018072522426994, 102.60476668117992, 23.06983994740403, 76.66341337442128, 40.89006992944426, 30.766128572726984, 60.38052488554921, 28.149186722890505, 100.20515752920485, 64.87845339634194, 11.63029761930508, 4.5780972047653785, 4.5781000857949135, 4.58105366240199, 3.939953658418966, 3.940382256381331, 3.301807128643857, 3.3018069999283552, 3.3018074517691667, 3.301806901166737, 3.3018091320318486, 3.301817729155603, 3.304659497028384, 3.3056951743934895, 3.306858877338131, 8.607845978004523, 2.663660393874457, 2.6636605025825504, 2.663660722688144, 2.663661447627641, 2.663661897442077, 2.663661530061515, 2.6636621338715267, 2.6636619349701043, 2.663663277871766, 2.663673801330379, 2.663675350258502, 2.6646034569908874, 2.6654958718944166, 9.33345250491164, 8.73185451466604, 9.606668710815704, 9.6091750682257, 15.44610422192773, 6.206773851095455, 49.64110977975771, 17.95530836066319, 12.881248778894333, 30.018072522426994, 20.30768011652516, 71.18839932045651, 14.315979021336421, 6.960296588359131, 129.93503980392296, 72.69264119776368, 72.0654886094549, 130.78782649179027, 28.11794484881038, 38.6766940680917, 154.5170162601466, 102.60476668117992, 6.998360616020252, 58.96863462637272, 76.66341337442128, 35.234005436209365, 42.59749501045614, 46.700980647743826, 31.089316231506743, 13.055142236406397, 60.38052488554921, 28.149186722890505, 64.69748955646716, 43.211015244755345, 78.95197787486738, 26.066151381364698, 19.53142451871473, 15.448519341498526, 57.487983469953065, 55.40982175280833, 13.812295577484303, 11.36565298465191, 10.549001087753485, 10.542870430998775, 8.915604972301365, 8.912892456544533, 10.518308384622475, 20.17015085094893, 8.098886512939252, 8.098514539311147, 8.097554569277492, 8.096773664849897, 8.096804399247613, 8.095960497844917, 8.097715738250663, 7.28092979474471, 7.277500015667297, 7.266971835469164, 8.075492794151714, 6.465523664242981, 6.465492237045607, 6.4655187792230455, 7.27622124345969, 17.872135054386597, 19.48137658999847, 33.06049061262334, 21.117064970724282, 21.115344253103515, 18.677228764951217, 21.115849234526472, 18.356100726271627, 100.20515752920485, 33.63143386305441, 15.40978113372327, 30.11395139779965, 65.29432066041552, 64.87845339634194, 14.601049696008502, 33.34649765001418, 45.264962828246716, 32.72164997647396, 36.337762247764864, 32.20008487025186, 28.143420600608657, 34.42327012145392, 43.80863032289488, 102.60476668117992, 47.07234105046067, 41.02348928191394, 60.38052488554921, 76.66341337442128, 130.78782649179027, 154.5170162601466, 34.779539953280114, 40.86056410270998, 72.0654886094549, 27.387199103017437, 40.89006992944426, 58.96863462637272], "Category": ["Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Default", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic1", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic2", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3", "Topic3"], "logprob": [30.0, 29.0, 28.0, 27.0, 26.0, 25.0, 24.0, 23.0, 22.0, 21.0, 20.0, 19.0, 18.0, 17.0, 16.0, 15.0, 14.0, 13.0, 12.0, 11.0, 10.0, 9.0, 8.0, 7.0, 6.0, 5.0, 4.0, 3.0, 2.0, 1.0, -5.5975, -5.9235, -6.7403, -6.9533, -7.0811, -7.0811, -7.0811, -7.0919, -7.2278, -7.2278, -7.228, -7.2326, -6.5609, -7.3996, -7.3997, -7.3997, -7.4007, -7.4019, -6.2952, -7.4066, -6.6467, -6.487, -6.2206, -7.6073, -7.6073, -7.6073, -7.6073, -7.6073, -7.6073, -7.6073, -6.8395, -6.8404, -6.6695, -6.2821, -6.953, -4.261, -6.6456, -6.411, -5.0005, -5.5726, -4.9294, -6.6614, -6.9591, -5.7175, -4.5333, -5.1777, -5.5916, -5.6908, -6.3232, -5.7202, -4.9322, -6.4114, -5.676, -6.4826, -5.8233, -5.7133, -6.372, -5.602, -5.7282, -6.1788, -6.0964, -6.1232, -5.5444, -6.2546, -5.729, -6.0147, -6.171, -6.0282, -6.2438, -6.1775, -6.2241, -5.6715, -6.666, -6.666, -6.6689, -6.8379, -6.8383, -7.0456, -7.0456, -7.0456, -7.0456, -7.0456, -7.0456, -7.0497, -7.0511, -7.0527, -6.1104, -7.308, -7.308, -7.308, -7.308, -7.308, -7.308, -7.308, -7.308, -7.308, -7.308, -7.308, -7.3098, -7.3114, -6.0594, -6.172, -6.2231, -6.2246, -5.9223, -6.6637, -5.1325, -5.9828, -6.2375, -5.6798, -5.9511, -5.1245, -6.1857, -6.6668, -4.7411, -5.1601, -5.2223, -4.898, -5.8099, -5.6501, -4.8869, -5.3015, -6.6641, -5.6033, -5.5231, -5.9139, -5.9137, -5.8974, -6.1217, -6.3899, -6.0822, -6.2684, -6.2253, -5.2252, -4.6278, -5.7364, -6.0328, -6.2726, -4.9654, -5.005, -6.3952, -6.5909, -6.6689, -6.6718, -6.8458, -6.8473, -6.6828, -6.0336, -6.9476, -6.9478, -6.9484, -6.9488, -6.9489, -6.9498, -6.9515, -7.0618, -7.0653, -7.0712, -6.966, -7.1888, -7.1888, -7.1888, -7.0715, -6.1742, -6.0907, -5.5869, -6.0325, -6.0336, -6.1529, -6.0352, -6.174, -4.5537, -5.6154, -6.3478, -5.726, -5.0285, -5.0481, -6.4078, -5.6564, -5.406, -5.7218, -5.6378, -5.7412, -5.8605, -5.7103, -5.5198, -4.8889, -5.4947, -5.611, -5.3826, -5.2532, -4.9323, -4.9502, -5.7635, -5.7046, -5.5979, -5.9294, -5.8436, -5.7698], "loglift": [30.0, 29.0, 28.0, 27.0, 26.0, 25.0, 24.0, 23.0, 22.0, 21.0, 20.0, 19.0, 18.0, 17.0, 16.0, 15.0, 14.0, 13.0, 12.0, 11.0, 10.0, 9.0, 8.0, 7.0, 6.0, 5.0, 4.0, 3.0, 2.0, 1.0, 0.9381, 0.8981, 0.8973, 0.8862, 0.8769, 0.8769, 0.8769, 0.8659, 0.8648, 0.8648, 0.8646, 0.86, 0.8486, 0.8485, 0.8484, 0.8484, 0.8474, 0.8462, 0.846, 0.8414, 0.8384, 0.8372, 0.8367, 0.825, 0.825, 0.825, 0.825, 0.825, 0.825, 0.825, 0.8162, 0.8153, 0.7976, 0.774, 0.8004, 0.6717, 0.7784, 0.7651, 0.6295, 0.6651, 0.5841, 0.763, 0.7947, 0.5833, 0.2261, 0.3567, 0.4564, 0.4537, 0.5855, 0.3514, -0.0061, 0.5952, 0.28, 0.6227, 0.2548, 0.1816, 0.5558, -0.0798, -0.0055, 0.3728, 0.2665, 0.2747, -0.3755, 0.4066, -0.2687, 0.0741, 0.2023, -0.3292, 0.2184, -0.985, -0.5969, 1.6747, 1.6124, 1.6124, 1.6089, 1.5907, 1.5901, 1.5597, 1.5597, 1.5597, 1.5597, 1.5597, 1.5597, 1.5547, 1.553, 1.551, 1.5367, 1.5121, 1.5121, 1.5121, 1.5121, 1.5121, 1.5121, 1.5121, 1.5121, 1.5121, 1.512, 1.512, 1.5099, 1.5079, 1.5067, 1.4607, 1.3141, 1.3125, 1.1401, 1.3103, 0.7624, 0.929, 1.0064, 0.7182, 0.8377, 0.4099, 0.9526, 1.1927, 0.1916, 0.3534, 0.2998, 0.0282, 0.6535, 0.4944, -0.1274, -0.1327, 1.19, 0.1195, -0.0628, 0.3239, 0.1343, 0.0586, 0.2411, 0.8407, -0.3832, 0.1939, -0.5953, 0.8084, 0.8031, 0.8027, 0.7949, 0.7896, 0.7827, 0.78, 0.779, 0.7782, 0.7748, 0.7724, 0.7661, 0.7649, 0.7639, 0.762, 0.7604, 0.7602, 0.7597, 0.7594, 0.7594, 0.7585, 0.7566, 0.7527, 0.7496, 0.7452, 0.7449, 0.7445, 0.7444, 0.7444, 0.7436, 0.7423, 0.7396, 0.7145, 0.7172, 0.7162, 0.7195, 0.7145, 0.7158, 0.6388, 0.6689, 0.7169, 0.6687, 0.5923, 0.5791, 0.7109, 0.6364, 0.5812, 0.5899, 0.5691, 0.5865, 0.6019, 0.5507, 0.5001, 0.2799, 0.4534, 0.4746, 0.3164, 0.2071, -0.0062, -0.1908, 0.4872, 0.385, -0.0757, 0.5603, 0.2452, -0.0471]}, "token.table": {"Topic": [2, 1, 1, 2, 1, 2, 3, 2, 1, 2, 3, 3, 1, 1, 2, 3, 1, 1, 2, 3, 1, 1, 2, 1, 2, 3, 2, 1, 1, 1, 2, 1, 2, 3, 1, 2, 3, 1, 3, 1, 2, 3, 3, 2, 3, 1, 2, 1, 2, 3, 1, 2, 3, 2, 1, 2, 3, 1, 2, 3, 1, 2, 1, 3, 3, 1, 2, 3, 1, 2, 1, 3, 2, 1, 2, 3, 1, 2, 3, 3, 1, 3, 3, 3, 1, 2, 3, 2, 1, 2, 3, 3, 2, 3, 1, 2, 2, 3, 2, 2, 1, 2, 1, 2, 3, 1, 1, 2, 3, 1, 2, 3, 1, 2, 3, 3, 2, 1, 3, 2, 3, 1, 2, 3, 3, 1, 2, 3, 1, 2, 3, 2, 1, 3, 1, 2, 1, 3, 2, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 1, 2, 3, 2, 1, 3, 1, 2, 3, 1, 3, 1, 2, 3, 1, 2, 3, 1, 2, 1, 2, 3, 1, 2, 3, 2, 2, 1, 1, 1, 3, 2, 1, 3, 1, 2, 3, 1, 2, 3, 3, 3, 2, 1, 2, 1, 2, 3, 3, 3, 2, 1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 1, 1, 2, 3, 2, 1, 2, 3, 1, 2, 3, 3, 1, 2, 2, 1, 2, 3, 1, 2, 3, 2, 1, 2, 3, 1, 1, 2, 3, 1, 2, 1, 2, 3, 1, 1, 2, 3, 1, 1, 3, 1, 2, 3, 1, 2, 3, 2, 3, 2, 1, 3, 1, 2, 3, 1, 3, 1, 2, 3, 1, 3, 2, 3, 3, 1, 3, 1, 3, 1, 2, 3, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 1, 2, 3, 1, 2, 3, 1, 1, 1, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 3, 1, 2, 3, 1, 1], "Freq": [0.7508459780118883, 0.9069187204751764, 0.9048247400033446, 0.12926067714333495, 0.5635062934826666, 0.04334663796020512, 0.39011974164184604, 0.7508460446577723, 0.033207199772297816, 0.09962159931689345, 0.8633871940797432, 0.961415670434361, 0.9069176288925985, 0.1428906075104013, 0.5715624300416052, 0.2857812150208026, 0.8476160293598255, 0.4789116551112582, 0.15532269895500267, 0.36241963089500623, 0.9939242478396783, 0.9044677920583785, 0.12920968457976836, 0.32008029208367883, 0.35564476898186537, 0.35564476898186537, 0.7614302756047763, 0.9511270402470071, 0.7643243823920473, 0.9161011079866369, 0.0916101107986637, 0.6790639243551975, 0.16976598108879937, 0.16976598108879937, 0.7379234826728005, 0.2554350516944309, 0.9880478732819202, 0.9106834839357758, 0.07005257568736736, 0.3000127308142262, 0.16957241306891047, 0.5348053027557945, 0.9280035889025654, 0.03478987919354189, 0.9567216778224019, 0.8203153394243701, 0.11718790563205286, 0.6878275321428025, 0.2476179115714089, 0.055026202571424196, 0.1699511819780569, 0.1274633864835427, 0.7010486256594848, 0.7503294306655832, 0.08715034886038568, 0.14525058143397615, 0.7553030234566759, 0.19882928069883946, 0.02209214229987105, 0.7953171227953578, 0.1161730823896341, 0.8132115767274387, 0.055953023908833804, 0.9512014064501747, 0.9879329256040578, 0.06049517000320464, 0.03024758500160232, 0.9074275500480695, 0.4310161157525101, 0.5746881543366801, 0.8476183780549497, 0.9879525888411277, 0.8731615682280994, 0.059976313584438744, 0.08996447037665811, 0.8396683901821423, 0.3900378590369064, 0.20349801341055987, 0.423954194605333, 0.9618687715465636, 0.7643243132634479, 0.9632622994125134, 0.9709668395019778, 0.972791307761217, 0.12224322437517358, 0.06112161218758679, 0.7945809584386283, 0.7505807270319247, 0.726457862928035, 0.09273930165038745, 0.1854786033007749, 0.8975761840507548, 0.054477800863708466, 0.9261226146830439, 0.6735342714829315, 0.30615194158315073, 0.6444571843541596, 0.3222285921770798, 0.9085904329331986, 0.750846375803303, 0.9668862043826605, 0.050888747599087396, 0.695252083132241, 0.06045670288106443, 0.24182681152425772, 0.8476179866435293, 0.10714148911924708, 0.7499904238347296, 0.10714148911924708, 0.07302681783839832, 0.14605363567679663, 0.7667815873031822, 0.7434128993817471, 0.0675829908528861, 0.2027489725586583, 0.9279990781230113, 0.750846171453687, 0.06848822658780283, 0.8903469456414369, 0.8737254411803156, 0.9485082896017962, 0.012665927148587976, 0.012665927148587976, 0.9879423175898622, 0.9279997792723159, 0.38229857733080813, 0.1835033171187879, 0.43582037815712127, 0.483894234854789, 0.12097355871369725, 0.3871153878838312, 0.7508456555357008, 0.09471784954233184, 0.8998195706521525, 0.764324657110695, 0.7508422525312274, 0.2157881279085695, 0.7860853230955032, 0.7508460340791885, 0.4633256609701899, 0.3827472851492873, 0.16115675164180518, 0.11007832493169113, 0.11007832493169113, 0.7705482745218379, 0.5139078380607724, 0.19271543927278964, 0.29977957220211726, 0.9206391858116443, 0.44318208423405026, 0.39393963043026686, 0.14772736141135007, 0.7508426891465069, 0.051331074853991035, 0.9239593473718386, 0.5478420693860588, 0.2668974184188492, 0.18261402312868627, 0.9252731398518138, 0.08411573998652853, 0.6662215820791585, 0.055518465173263205, 0.22207386069305282, 0.5528876638096034, 0.09615437631471364, 0.36057891118017615, 0.8891887360363492, 0.09879874844848324, 0.5438100833196118, 0.1165307321399168, 0.3495921964197504, 0.4550458783563192, 0.16251638512725686, 0.3575360472799651, 0.7508461482168163, 0.7613474543343073, 0.7643240069340822, 0.7643245689171473, 0.036094683879733545, 0.956509122812939, 0.8737248913389504, 0.2875253673117342, 0.7188134182793355, 0.3607829559153066, 0.23589654809846972, 0.4024117585209189, 0.11452320905260138, 0.8016624633682097, 0.11452320905260138, 0.9951166330260903, 0.8973031022408542, 0.9085933853992968, 0.7979763735586055, 0.1450866133742919, 0.26314566928353456, 0.1559381743902427, 0.5847681539634102, 0.9620378168533599, 0.9479570545887203, 0.7508464378478042, 0.41574886101524083, 0.024455815353837698, 0.562483753138267, 0.9878354803423585, 0.9085932610614671, 0.28154773467477073, 0.11593142016019972, 0.5962187322524557, 0.9458055468624593, 0.8364513969361747, 0.09293904410401942, 0.9512865545565531, 0.19501022804335094, 0.09750511402167547, 0.7069120766571472, 0.9075246935163716, 0.20818871350776283, 0.6245661405232885, 0.10409435675388141, 0.3829908483154387, 0.3829908483154387, 0.1531963393261755, 0.9411904000368743, 0.8202783447966627, 0.11718262068523753, 0.9085934125765837, 0.4455506883706071, 0.4455506883706071, 0.11138767209265177, 0.4618250654264406, 0.21315003019681872, 0.3197250452952281, 0.9078091109530831, 0.4889641141250106, 0.4889641141250106, 0.06985201630357295, 0.9069221493480006, 0.13971336750725322, 0.019959052501036176, 0.8283006787930013, 0.901804190820223, 0.06441458505858737, 0.08920226274668681, 0.059468175164457876, 0.8622885398846393, 0.9857332877947106, 0.16846794466564863, 0.030630535393754297, 0.7963939202376117, 0.9512864730298378, 0.8476188751592161, 0.9880441227829823, 0.23289667418856466, 0.4657933483771293, 0.3105288989180862, 0.8363770372145943, 0.06433669517035341, 0.06433669517035341, 0.9072053302785215, 0.9678282466352189, 0.9085933499792832, 0.09471558438340263, 0.8997980516423251, 0.7542230344323273, 0.2154922955520935, 0.03848076706287384, 0.8733512869172718, 0.09703903187969687, 0.20813441172628078, 0.6244032351788423, 0.10406720586314039, 0.06489384835009547, 0.9085138769013364, 0.04957821125829378, 0.9419860139075817, 0.866820165460294, 0.847510936974662, 0.9974621730535951, 0.09471013148715066, 0.8997462491279312, 0.6103645295015104, 0.21128002944283053, 0.18780447061584934, 0.9085927986860576, 0.7508464684910067, 0.9881471138760545, 0.9507232184425939, 0.9877901100625048, 0.2054389724961682, 0.06847965749872273, 0.7304496799863758, 0.18633491259965956, 0.031055818766609927, 0.7763954691652482, 0.8368107116793089, 0.1859579359287353, 0.5146462495622587, 0.2251577341834882, 0.2894885153787705, 0.4996989726370091, 0.36644591326714, 0.1332530593698691, 0.8476054790335913, 0.7643243423293306, 0.7643245622656331, 0.31815517689188744, 0.024473475145529805, 0.6363103537837749, 0.32370621926154414, 0.5826711946707794, 0.12948248770461765, 0.5946733699500707, 0.28440900301959904, 0.10342145564349056, 0.10708226713767639, 0.9101992706702494, 0.14212913407951172, 0.03553228351987793, 0.8172425209571924, 0.9069175527888459, 0.9512866683421312], "Term": ["'paederos", "'smaragdi", "1/2", "1/2", "according", "according", "according", "adulterate", "alexander", "alexander", "alexander", "alexandria", "aloe", "alone", "alone", "alone", "alp", "also", "also", "also", "amber", "amethyst", "amethyst", "another", "another", "another", "bdellium", "beast", "belief", "beryl", "beryl", "bird", "bird", "bird", "black", "black", "breadth", "call", "call", "called", "called", "called", "chain", "city", "city", "closely", "closely", "colour", "colour", "colour", "come", "come", "come", "contained", "country", "country", "country", "day", "day", "day", "denarii", "denarii", "desert", "desert", "direction", "distance", "distance", "distance", "dog", "dog", "drop", "dwell", "ebony", "elephant", "elephant", "elephant", "even", "even", "even", "extent", "exudation", "fifteen", "fifty", "five", "foot", "foot", "foot", "foreign", "found", "found", "found", "founded", "ganges", "ganges", "gem", "gem", "genuine", "genuine", "gingelly", "ginger", "glass", "glass", "gold", "gold", "gold", "graft", "grain", "grain", "grain", "great", "great", "great", "greek", "greek", "greek", "harbour", "heavier", "horse", "horse", "hound", "hour", "hundred", "hundred", "hundred", "ichthyophagi", "india", "india", "india", "indian", "indian", "indian", "indigo", "indus", "indus", "ink", "irio", "island", "island", "juniper", "kind", "kind", "kind", "king", "king", "king", "known", "known", "known", "layer", "leaf", "leaf", "leaf", "lentisk", "lie", "lie", "like", "like", "like", "linen", "linen", "live", "live", "live", "made", "made", "made", "magi", "magi", "make", "make", "make", "many", "many", "many", "master", "mastich", "meleager", "midwinter", "mile", "mile", "millet", "mountain", "mountain", "name", "name", "name", "nard", "nard", "nard", "nation", "navigable", "nonius", "occurs", "occurs", "one", "one", "one", "onesicritus", "opposite", "panic", "part", "part", "part", "parthia", "peck", "people", "people", "people", "pepper", "piece", "piece", "pine", "place", "place", "place", "pod", "pound", "pound", "pound", "price", "price", "price", "promontory", "property", "property", "pungency", "purple", "purple", "purple", "red", "red", "red", "reign", "resembles", "resembles", "resembles", "respect", "river", "river", "river", "rock-crystal", "rock-crystal", "salt", "salt", "salt", "sardonyx", "sea", "sea", "sea", "shed", "shining", "situate", "small", "small", "small", "sometimes", "sometimes", "sometimes", "spoken", "stadium", "stalk", "stated", "stated", "stone", "stone", "stone", "story", "story", "taste", "taste", "taste", "territory", "territory", "thence", "thence", "thirty", "thoroughly", "thousand", "town", "town", "tree", "tree", "tree", "triumph", "tuft", "twelve", "twenty", "twenty-five", "two", "two", "two", "upon", "upon", "upon", "use", "use", "used", "used", "used", "variety", "variety", "variety", "vermilion", "vinegar", "washed", "water", "water", "water", "weight", "weight", "weight", "white", "white", "white", "whose", "whose", "writer", "writer", "writer", "writes", "xenocrates"]}, "R": 30, "lambda.step": 0.01, "plot.opts": {"xlab": "PC1", "ylab": "PC2"}, "topic.order": [1, 2, 3]};

function LDAvis_load_lib(url, callback){
  var s = document.createElement('script');
  s.src = url;
  s.async = true;
  s.onreadystatechange = s.onload = callback;
  s.onerror = function(){console.warn("failed to load library " + url);};
  document.getElementsByTagName("head")[0].appendChild(s);
}

if(typeof(LDAvis) !== "undefined"){
   // already loaded: just create the visualization
   !function(LDAvis){
       new LDAvis("#" + "ldavis_el887629447782910082926906180", ldavis_el887629447782910082926906180_data);
   }(LDAvis);
}else if(typeof define === "function" && define.amd){
   // require.js is available: use it to load d3/LDAvis
   require.config({paths: {d3: "https://d3js.org/d3.v5"}});
   require(["d3"], function(d3){
      window.d3 = d3;
      LDAvis_load_lib("https://cdn.jsdelivr.net/gh/bmabey/pyLDAvis@3.3.1/pyLDAvis/js/ldavis.v3.0.0.js", function(){
        new LDAvis("#" + "ldavis_el887629447782910082926906180", ldavis_el887629447782910082926906180_data);
      });
    });
}else{
    // require.js not available: dynamically load d3 & LDAvis
    LDAvis_load_lib("https://d3js.org/d3.v5.js", function(){
         LDAvis_load_lib("https://cdn.jsdelivr.net/gh/bmabey/pyLDAvis@3.3.1/pyLDAvis/js/ldavis.v3.0.0.js", function(){
                 new LDAvis("#" + "ldavis_el887629447782910082926906180", ldavis_el887629447782910082926906180_data);
            })
         });
}
</script>
</div>
</div>
<div class="cell" data-execution_count="39">
<div class="cell-output cell-output-display" data-execution_count="39">
<div id="fig-topic_cluster0" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;8: Topic cluster (overall)</figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-topic_cluster0-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-execution_count="40">
<div class="cell-output cell-output-display" data-execution_count="40">
<div id="fig-topic_cluster1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;9: Topic cluster (highlighting on Topic_0)</figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-topic_cluster1-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-execution_count="41">
<div class="cell-output cell-output-display" data-execution_count="41">
<div id="fig-topic_cluster2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;10: Topic cluster (highlighting on Topic_1)</figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-topic_cluster2-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-execution_count="42">
<div class="cell-output cell-output-display" data-execution_count="42">
<div id="fig-topic_cluster3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;11: Topic cluster (highlighting on Topic_2)</figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-topic_cluster3-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>In the above visualisation, the three keyword clusters are distanced from each other, indicating that they formed distinct potential topics within the given text. And the first (about stones) and the last (about Indian geography and society) topics took up a more significatnt portion comparing to the second topic (about merchandise trade).</p>
<p>Additionally, the specific context of the Indian places mentioned in <em>Natural History</em> is manually summarized and categorized into broader types to serve as a comparison and extension to the topics generated by the model. The innitial comments about the context were drawn upon a close reading of the related text, with consideration of the book and chapter theme indicated in the text. The comments and summary are stored in CSV format and imported as pandas data frame.</p>
<div class="cell" data-execution_count="87">
<div class="cell-output cell-output-display">
<p>And the summarized comments were further categorized into seven types, namely [‘geographical reference’, ‘conquest history’, ‘passing mention’, ‘general introduction’, ‘criticism’, ‘prominent features’, ‘goods/animals/plants origin’, ‘producing activity’, ‘product/knowledge exchange’].</p>
</div>
</div>
<p><strong>Geographical reference</strong>: refers to the occurence of Indian place names as geographical reference in the narrative, for example:</p>
<blockquote class="blockquote">
<p>2.112.1 “…from the river <strong>Ganges</strong> and its mouth where it flows into the Eastern Ocean, through <strong>India</strong> and Parthyene to the Syrian city of Myriandrus situated on the Issic gulf 5,215…”</p>
</blockquote>
<p><strong>Passing mention</strong>: refers to the condition that the names of Indian place included as a side note, for example:</p>
<blockquote class="blockquote">
<p>5.11.1 “…Coptos, which from its proximity to the Nile, forms its nearest emporium for the merchandise of <strong>India</strong> and Arabia…”</p>
</blockquote>
<p><strong>Conquest history</strong>: refers to the mentions of Indian place names in the context of recalling the conquest history of Alexader the Great, for example:</p>
<blockquote class="blockquote">
<p>8.61.2 “…When Alexander the Great was on his way to <strong>India</strong>, the king of Albania had presented him with one dog of unusually large size…”</p>
</blockquote>
<p><strong>General introduction</strong>: refers to the focused introduction about the general situation of places in Indian subcontinent, including transportation in the work, it is normally directly indicated at the begining of the affiliated chapter. For example, the whole chapter 21 of book 6 has a leading topic as “The nations of India”, the whole chapter 22 of book 6 has a leading topic as “The Ganges”.</p>
<p><strong>Prominent features</strong>: in <em>Natural History</em>, the plants and animals from India are often noted for their large size, and Pliny often highlight the good quality of Indian products in his discussion, these genre of context is categorize as “prominent features” of India. For example:</p>
<blockquote class="blockquote">
<p>8.14.1 “…Megasthenes writes that in <strong>India</strong> snakes grow so large as to be able to swallow stags and bulls whole…” 37.21.1 “…<strong>India</strong>, likewise, is the sole producer of these stones and combining, as they do, the brilliant qualities of the most valuable gems, they above all others description…”</p>
</blockquote>
<p><strong>Goods/animals/plants origin</strong>: there are also many descriptions about India as the origin of different goods, animals and plants, this genre refers to those without concrete comments on their size or quality, just simply mentioned the object is originated in India, for example:</p>
<blockquote class="blockquote">
<p>8.25.2 “Hyrcania and <strong>India</strong> produce the tiger, au animal of terrific speed…”</p>
</blockquote>
<p><strong>Producing activity</strong>: this genre refer to the cases that introduces about the human activity or specific producing process about natural creatures or trading products, such as:</p>
<blockquote class="blockquote">
<p>8.8.1 “The method of capturing them in <strong>India</strong> is for a mahout riding one of the domesticated elephants…” 37.20.1 “…The <strong>Indians</strong> have found a way of counterfeiting various precious stones, and beryls in particulars by staining rock-crystal.”</p>
</blockquote>
<p><strong>Criticism</strong>: woven in the description about merchandise trade with Indian subcontinent, Pliny had drwan direct criticism about the human greed and unnecessary interference on nature it represents, hence these narratives are specificly grouped together, for example:</p>
<blockquote class="blockquote">
<p>12.14.2 “To think that its only pleasing quality is pungency and that we go all the way to India to get this! Who was the first person who was willing to try it on his viands, or in his greed for an appetite was not content merely to be hungry?”</p>
</blockquote>
<blockquote class="blockquote">
<p>22.56.1 “I myself shall not touch upon drugs imported from India and Arabia or from the outer world. Ingredients that grow so far away are unsatisfactory for remedies…Let them be bought if you like to make perfumes, unguents and luxuries, or even in the name of religion, for we worship the gods with frankincense and costmary. But health I shall prove to be independent of such drugs, if only to make luxury all the more ashamed of itself.”</p>
</blockquote>
<blockquote class="blockquote">
<p>33.2.1 “It came to be deemed the proof of wealth, the true glory of luxury, to possess something that might be absolutely destroyed in a moment. Nor was this enough: we drink out of a crowd of precious stones, and set our cups with emeralds, we take delight in holding India for the purpose of tippling, and gold is now a mere accessory.”</p>
</blockquote>
<p><strong>Product/knowledge exchange</strong>: in some circumstances, Pliny also mentioned about the knowledge and product exchange during the trade, such as:</p>
<blockquote class="blockquote">
<p>34.48.3 “India possesses neither copper nor lead, and procures them in exchange for her precious stones and pearls.”</p>
</blockquote>
<blockquote class="blockquote">
<p>37.23.2 “…Indeed, as is generally known, in India the stone is exposed to view by the mountain streams…Later we persuaded the Indians to share our appreciation of it.”</p>
</blockquote>
<p>And the distribution of context type concluded from close reading is shown in <a href="#fig-book_context_distribution">Figure&nbsp;12</a> and <a href="#fig-context_type_freq">Figure&nbsp;13</a>.</p>
<div class="cell" data-execution_count="24">
<div class="cell-output cell-output-display">
<div id="fig-book_context_distribution" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;12: Context type distribution in books containing Indian place names</figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-book_context_distribution-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-execution_count="25">
<div class="cell-output cell-output-display">
<div id="fig-context_type_freq" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;13: Occurence frequency of different context type in India-related text</figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-context_type_freq-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>In general, the contexts concluded from the close reading can relate to the latent topics generated from the distant reading method and added more details to the keywords clusters. That is, if we understand the content about India in <em>Natural History</em> in three main topics, namely stons, trade, and contrasting nation, under the “stone” topic, except for describing the colour and texture of different types of gemstone, there also include the description about India as an origin of gemstones in a high quality. And under the large proportion of Indian places as geographical reference and focused introduction mentioned in the narrative, contributes to the formation of “nation” condition as a major topic. Additionally, there were conquest history of the Roman Empire to Indian subcontinent referred in the description. And for the topic about “trade”, though it seem inferior to the previous two in terms of quantity, but it is this part that reflects more sentimental judgement from Pliny out of his stoicism standpoint that worshiping nature as a devine and against luxurious desire <span class="citation" data-cites="beagon1996">(<a href="#ref-beagon1996" role="doc-biblioref">Beagon 1996</a>)</span>.</p>
<p>On top of the observation from the previous section, that India is seen as an important geographical contrast, as well as a significant trading partner in the narrative, a more nuanced protrait of India, linking the conquest story/history of the Roman Empire and criticism aobut human greed from the stoicism with abundant natural wonders and products of the best quality in the world can be drawn from the comprehension of topic modelling and close reading.</p>
</section>
<section id="network-analysis-for-named-entity" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="network-analysis-for-named-entity"><span class="header-section-number">4.4</span> Network analysis for Named Entity</h3>
<p>In addition to the previous methods partly answered on the question about “how India is described?” in <em>Natural History</em>, a network analysis of the named entities in the text may shed a light on the structure of the India-related content in the work. As inspired by the person name collocations observed from the collocation analysis, the initial idea for this section is to extract person names mentioned in the India-related text, and generate a entity cluster for the person names, place names, and book number, to explore how the content is structured in the context.</p>
<p>Employing the dataset with supplemented Indian place name annotations, distinct place names (including annotated places outside Indian subcontinenet), person names and book numbers are considered as nodes, and the co-occurences of person name and place names, as well as that of two different place names in the same paragraph, and the book number the person and place name occured, are counted as edges.</p>
<p>To identify the the impact of different entities in the discourse, the betweeness centrality of the nodes are mesured and represented by the size of the node. And the weight of edge between two nodes represents the time the two entities appeared in the same context. Gone through a Force Atlas 2 layout algorithm, the graph also demonstrates the rough cluster of entities which tend to be mentioned together.</p>
<div class="cell" data-execution_count="29">
<div class="cell-output cell-output-display">
<p>Indexing with the book-chapter-paragraph number of the India-related text, the place names outside Indian subcontinent mentioned in the same paragraph are also included for the network analysis. And according to the original TOPOSText and supplemented place name annotations, there are total of 908 occurences of place names in paragraphs of Indian-related text in <em>Natural History</em>.</p>
</div>
</div>
<section id="person-name-annotationtag-retrieve" class="level4" data-number="4.4.1">
<h4 data-number="4.4.1" class="anchored" data-anchor-id="person-name-annotationtag-retrieve"><span class="header-section-number">4.4.1</span> Person name annotation/tag retrieve</h4>
<p>In order to extract the people names within the captioned text, approaches of retriving from the TOPOSText annotation and from the tagging of text given by the pretrained multilingual named entity recognition model <a href="https://huggingface.co/Babelscape/wikineural-multilingual-ner">WikiNEuRal</a> <span class="citation" data-cites="tedeschi2021">(<a href="#ref-tedeschi2021" role="doc-biblioref">Tedeschi et al. 2021</a>)</span> and <a href="https://huggingface.co/flair/ner-english-ontonotes-fast">Flair</a> <span class="citation" data-cites="akbik2018coling">(<a href="#ref-akbik2018coling" role="doc-biblioref">Akbik, Blythe, and Vollgraf 2018</a>)</span> are compared for adopting the most completed output.</p>
<p><strong>1. Annotation retrieving from TOPOSText</strong></p>
<p>On TOPOSText, other than place names, a list of proper names (including people, gods, festivals, animals and artworks) are also annotated to the text of the classics. Each proper name has a unique URI as identifier in the html structure, such as: **&lt;a href=“/people/54” target=“_blank”&gt;Muses&lt;/a&gt;**.</p>
<p>Utilizing the tools of <a href="https://www.crummy.com/software/BeautifulSoup/bs4/doc/">Beautiful Soup</a>, the textual proper names, their URIs along with the book-chapter-paragraph number they occured in, can be retrieved with the URLs of both parts of <em>Natural History</em> on TOPOSText.</p>
<div class="cell" data-execution_count="35">
<div class="cell-output cell-output-display">
<p>In the annotated text of <em>Natural History</em> on TOPOSText, there are 5109 such proper name annotations in book 1-11 and 7038 in book 12-37, adding up to a combined total of 12147 throughout the work.</p>
</div>
</div>
<p>The specific annotation type as “person name” can be further validated with the <a href="https://topostext.org/api/people/readweb.php">api</a> on TOPOText. In the api file, all the entities of people/gods, has been valued as “male” or “female” as its “gender” key. Based on this criteria, those with other values in their “gender” key, such as “gender”:“animal” or “gender”:“other”, are not considered as “people” and filtered out from the retrieved output. Moreover, as there is a “concat” value indicating a detailed name of the signified person and shared with all variants of the same URI, the “concat” value is also fetched as a more accurate information of person name enetity.</p>
<div class="cell" data-execution_count="40">
<div class="cell-output cell-output-display" data-execution_count="40">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<div id="tbl-validated_people_anno" class="anchored">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Table&nbsp;7: Example of retrieved and validated person name annotations in <em>Naturl History</em></caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">FILE_ID</th>
<th data-quarto-table-cell-role="th">Person_name</th>
<th data-quarto-table-cell-role="th">ToposText_ID</th>
<th data-quarto-table-cell-role="th">Reference</th>
<th data-quarto-table-cell-role="th">Person_name_concat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1.1.1</td>
<td>Muses</td>
<td>/people/54</td>
<td>urn:cts:latinLit:phi0978.phi001:1.1.1</td>
<td>Muses (goddesses)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1.1.1</td>
<td>Catullus</td>
<td>/people/1881</td>
<td>urn:cts:latinLit:phi0978.phi001:1.1.1</td>
<td>Catullus</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1.2.1</td>
<td>Cicero</td>
<td>/people/2300</td>
<td>urn:cts:latinLit:phi0978.phi001:1.2.1</td>
<td>Marcus Tullius Cicero</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>1.2.1</td>
<td>Cicero</td>
<td>/people/2300</td>
<td>urn:cts:latinLit:phi0978.phi001:1.2.1</td>
<td>Marcus Tullius Cicero</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>1.2.1</td>
<td>Manius</td>
<td>/people/382</td>
<td>urn:cts:latinLit:phi0978.phi001:1.2.1</td>
<td>Manius</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</div>
<div class="cell" data-execution_count="91">
<div class="cell-output cell-output-display">
<p>An example of the data structure of the retrieved output of person name annotations in <em>Natural History</em> is shown in <a href="#tbl-validated_people_anno">Table&nbsp;7</a>. There are total 6568 occurences of person names annotated in the whole work, <strong>330</strong> of which are within the India-related text.</p>
</div>
</div>
<div class="cell" data-execution_count="79">
<div class="cell-output cell-output-display" data-execution_count="79">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<div id="tbl-person_anno_merged" class="anchored">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Table&nbsp;8: Example for person name annotation merged into India-related text dataset</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">FILE_ID</th>
<th data-quarto-table-cell-role="th">Place_Name</th>
<th data-quarto-table-cell-role="th">Book</th>
<th data-quarto-table-cell-role="th">Text</th>
<th data-quarto-table-cell-role="th">Person_name_concat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2.75.1</td>
<td>Syene</td>
<td>2.0</td>
<td>Similarly it is reported that at the town of S...</td>
<td>Onesicritus</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2.75.1</td>
<td>Syene</td>
<td>2.0</td>
<td>Similarly it is reported that at the town of S...</td>
<td>Alexander III, the Great (general)</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2.75.1</td>
<td>Syene</td>
<td>2.0</td>
<td>Similarly it is reported that at the town of S...</td>
<td>Alexander III, the Great (general)</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2.75.1</td>
<td>Syene</td>
<td>2.0</td>
<td>Similarly it is reported that at the town of S...</td>
<td>Onesicritus</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2.75.1</td>
<td>India</td>
<td>2.0</td>
<td>Similarly it is reported that at the town of S...</td>
<td>Onesicritus</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</div>
<div class="cell" data-scrolled="true" data-execution_count="92">
<div class="cell-output cell-output-display">
<p>As shown in <a href="#tbl-person_anno_merged">Table&nbsp;8</a>, the validated annotated person names are added to the India-related text dataset. With the person name annotation retrieving, there found total <strong>3583</strong> co-occurences of single place name and person name in the same paragraph within the India-related text in <em>Natural History</em>.</p>
</div>
</div>
<p><strong>2. Named entity recognition with <a href="https://huggingface.co/Babelscape/wikineural-multilingual-ner">WikiNEuRal</a></strong></p>
<p>To evaluate the quality and completeness of the extracted person name annotations, two widely practiced pretrained machine learning models for named entity recognition, <a href="https://huggingface.co/Babelscape/wikineural-multilingual-ner">WikiNEuRal</a> <span class="citation" data-cites="tedeschi2021">(<a href="#ref-tedeschi2021" role="doc-biblioref">Tedeschi et al. 2021</a>)</span> and <a href="https://huggingface.co/flair/ner-english-ontonotes-fast">Flair</a> <span class="citation" data-cites="akbik2018coling">(<a href="#ref-akbik2018coling" role="doc-biblioref">Akbik, Blythe, and Vollgraf 2018</a>)</span> are utilized for tagging person names in the India-related text.</p>
<div class="cell" data-execution_count="86">
<div class="cell-output cell-output-display" data-execution_count="86">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<div id="tbl-wiki_ppl_tag" class="anchored">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Table&nbsp;9: Example of person name tags retrieved with WikiNEuRal from India-related text in <em>Natural History</em></caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">FILE_ID</th>
<th data-quarto-table-cell-role="th">Text</th>
<th data-quarto-table-cell-role="th">Text_ner</th>
<th data-quarto-table-cell-role="th">PER_name_tag</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2.75.1</td>
<td>Similarly it is reported that at the town of S...</td>
<td>[{'entity_group': 'LOC', 'score': 0.99636984, ...</td>
<td>Onesicritus</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0</td>
<td>2.75.1</td>
<td>Similarly it is reported that at the town of S...</td>
<td>[{'entity_group': 'LOC', 'score': 0.99636984, ...</td>
<td>Alexander</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2.75.1</td>
<td>Similarly it is reported that at the town of S...</td>
<td>[{'entity_group': 'LOC', 'score': 0.99636984, ...</td>
<td>Alexander</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0</td>
<td>2.75.1</td>
<td>Similarly it is reported that at the town of S...</td>
<td>[{'entity_group': 'LOC', 'score': 0.99636984, ...</td>
<td>Onesicritus</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">21</td>
<td>2.112.1</td>
<td>Our own portion of the earth, which is my subj...</td>
<td>[{'entity_group': 'LOC', 'score': 0.7412269, '...</td>
<td>Artemidorus</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</div>
<div class="cell" data-execution_count="89">
<div class="cell-output cell-output-display">
<p>An example of the person name tags retrieved from WikiNEuRal of the given text are shown in <a href="#tbl-wiki_ppl_tag">Table&nbsp;9</a>. There are total <strong>225</strong> occurences retrieved within the India-related text.</p>
</div>
</div>
<div class="cell" data-execution_count="90">
<div class="cell-output cell-output-display">
<p>And after merging the person name tags with the dataset of place name occurences, there found total <strong>1881</strong> co-occurences of single place name and person name in the same paragraph within the India-related text in <em>Natural History</em>.</p>
</div>
</div>
<p><strong>3. Named entity recognition with <a href="https://huggingface.co/flair/ner-english-ontonotes-fast">Flair</a></strong></p>
<p>As a comparison, another well-esteemed NLP pretrained model, <a href="https://huggingface.co/flair/ner-english-ontonotes-fast">Flair</a> <span class="citation" data-cites="akbik2018coling">(<a href="#ref-akbik2018coling" role="doc-biblioref">Akbik, Blythe, and Vollgraf 2018</a>)</span> is also applied for the named enetity recognition to the same text.</p>
<div class="cell" data-execution_count="97">
<div class="cell-output cell-output-display" data-execution_count="97">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<div id="tbl-flair_ppl_tag" class="anchored">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Table&nbsp;10: Example of person name tags retrieved with Flair from India-related text in <em>Natural History</em></caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">FILE_ID</th>
<th data-quarto-table-cell-role="th">Text</th>
<th data-quarto-table-cell-role="th">Text_ner</th>
<th data-quarto-table-cell-role="th">PER_name_tag</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2.75.1</td>
<td>Similarly it is reported that at the town of S...</td>
<td>[{'entity_group': 'LOC', 'score': 0.99636984, ...</td>
<td>Leo</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0</td>
<td>2.75.1</td>
<td>Similarly it is reported that at the town of S...</td>
<td>[{'entity_group': 'LOC', 'score': 0.99636984, ...</td>
<td>Alexander</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2.75.1</td>
<td>Similarly it is reported that at the town of S...</td>
<td>[{'entity_group': 'LOC', 'score': 0.99636984, ...</td>
<td>Alexander</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0</td>
<td>2.75.1</td>
<td>Similarly it is reported that at the town of S...</td>
<td>[{'entity_group': 'LOC', 'score': 0.99636984, ...</td>
<td>Onesicritus</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">66</td>
<td>4.17.4</td>
<td>Such is Macedonia, which was once the mistress...</td>
<td>[{'entity_group': 'LOC', 'score': 0.95384216, ...</td>
<td>Paulus Aemilius</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</div>
<div class="cell" data-execution_count="98">
<div class="cell-output cell-output-display">
<p>An example of the person name tags retrieved from WikiNEuRal of the given text are shown in <a href="#tbl-flair_ppl_tag">Table&nbsp;10</a>. There are total <strong>102</strong> occurences retrieved within the India-related text.</p>
</div>
</div>
<div class="cell" data-execution_count="99">
<div class="cell-output cell-output-display">
<p>And after merging the person name tags with the dataset of place name occurences, there found total <strong>938</strong> co-occurences of single place name and person name in the same paragraph within the India-related text in <em>Natural History</em> with the NER tool of Flair.</p>
</div>
</div>
<p>As shown in <a href="#tbl-ner_compare">Table&nbsp;11</a>, the TOPOSText annotation provide more person name entities comparing to the other two methods.</p>
<div class="cell" data-execution_count="108">
<div class="cell-output cell-output-display" data-execution_count="108">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<div id="tbl-ner_compare" class="anchored">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Table&nbsp;11: Quantity of person name entities retrieved with different methods</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Distinct person name</th>
<th data-quarto-table-cell-role="th">Person name occurence</th>
<th data-quarto-table-cell-role="th">Place-person co-occurence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">TOPOSText Annotation</td>
<td>153</td>
<td>330</td>
<td>3583</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">WikiNEuRal NER</td>
<td>121</td>
<td>225</td>
<td>1881</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Flair NER</td>
<td>71</td>
<td>102</td>
<td>938</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</div>
<p>And the first fifteen distinct retrieved person names of the three methods can be referred in <a href="#tbl-per_name_compare">Table&nbsp;12</a>. For the case of “Alexander III, the Great (general)”, since the annotation retrieved from TOPOSText is validated with the URI, both “Alexander” and “Alexander the Great” will be recognized as the same entity. While from the output of WikiNEuRal and Flair, the two variants are recognized as two different entities. And for the case “Leo” retrieved from Flair NER, it actually refers to the zodiac constellation, rather than a person/god name, and the same entity has a “gender”:“astronomic” value in the TOPOSText annotation, which will prevent it being added to the dataset as a person name.</p>
<div class="cell" data-execution_count="137">
<div class="cell-output cell-output-display" data-execution_count="137">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<div id="tbl-per_name_compare" class="anchored">
<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<caption>Table&nbsp;12: First 15 distinct person names retrieved with different methods</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">TOPOSText Annotation</th>
<th data-quarto-table-cell-role="th">WikiNEuRal NER</th>
<th data-quarto-table-cell-role="th">Flair NER</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Onesicritus</td>
<td>Onesicritus</td>
<td>Leo</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Alexander III, the Great (general)</td>
<td>Alexander</td>
<td>Alexander</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Heracles (s. of Zeus), Hercules</td>
<td>Artemidorus</td>
<td>Onesicritus</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Artemidorus Ephesius</td>
<td>Isidore</td>
<td>Paulus Aemilius</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Isidoros of Charax</td>
<td>Father Liber</td>
<td>Cyrus</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Dionysus (s. of Zeus), Bacchus</td>
<td>Hercules</td>
<td>SCYTHIA</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>Paulus</td>
<td>Paulus Aemilius</td>
<td>Aramii</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>Aemilius</td>
<td>Amasis</td>
<td>M. Varro</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>Amasis</td>
<td>Alexander the Great</td>
<td>Pompey</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>Memnon (s. of Tithonus)</td>
<td>Antiochus</td>
<td>Laros</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>Osiris</td>
<td>Seleucus</td>
<td>Hecataeus</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>Calliope (d. of Zeus)</td>
<td>M</td>
<td>Patrocles</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>Antiochus, Antiochos (misc)</td>
<td>Varro</td>
<td>Alexander the Great</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>Seleucus I Nicator s. Antiochus</td>
<td>Amometus</td>
<td>Baeton</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>Margos</td>
<td>Hecataeus</td>
<td>Protalis</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</div>
<p>Both in terms of quantity and quality, the person names retrieved from the TOPOSText is more reliable for this study. Therefore, the output of TOPOSText annotation retriving is appended to the dataset for node/edge generation for the network analysis.</p>
</section>
<section id="network-graph-generation" class="level4" data-number="4.4.2">
<h4 data-number="4.4.2" class="anchored" data-anchor-id="network-graph-generation"><span class="header-section-number">4.4.2</span> Network graph generation</h4>
<p>As mentioned, there will be three types of nodes for the expected network graph, namely <strong>place name</strong>, <strong>person name</strong> and <strong>book number</strong>.</p>
<p>And there are four types of edges taken into consideration, including the co-occurence of:</p>
<ol type="1">
<li><strong>place name</strong> and <strong>person name</strong> in the same paragraph<br></li>
<li><strong>person name</strong> and <strong>book number</strong> it appears in<br></li>
<li><strong>place name</strong> and <strong>book number</strong> it appears in<br></li>
<li><strong>place name</strong> and <strong>place name</strong> in the same paragraph<br></li>
</ol>
<div class="cell" data-execution_count="141">
<div class="cell-output cell-output-display">
<p>There are total 519 nodes and 14177 edges for the network of place name/person name/book number in India-related text of <em>Natural History</em>.</p>
</div>
</div>
<p>The network graph generated from the captioned nodes and edges can be explored as <a href="#fig-network_graph">Figure&nbsp;14</a>. The size of the nodes represents the betweeness centralality of the entity in the context, which means the bigger the node, the more central it is in the discourse. The types of nodes (place name, person name, book number) are differenciated by colour.</p>
<p>And the curved lines linking different nodes indicate the co-occurences between single place name and person name, two place names, and the book number of place name and person name occurs. The thickness of the line represent the counts of the co-occurence edge, which means, the thicker the line linking, the more frequent the two nodes are mentioned together.</p>
<p>Apparently, “India” is the absolute center of the discourse. And drawing from both the node size and edge thickness, “Arabia” is the place that often mentioned together with India. Actually, the two countries are often mentioned in the same time, for example:</p>
<blockquote class="blockquote">
<p>13.28.1 “Ethiopia, which is on the borders of Egypt, has virtually no remarkable trees except the wool-tree, like the one described among the trees of <strong>India</strong> and <strong>Arabia</strong>.”</p>
</blockquote>
<blockquote class="blockquote">
<p>22.56.1 “I myself shall not touch upon drugs imported from <strong>India</strong> and <strong>Arabia</strong> or from the outer world.”</p>
</blockquote>
<p>One possible reason for this pairing occurence is that Arabia locates in the middle of the route from Rome to India, and the two places similarly are significant importers for the exotic and luxurious goods trade.</p>
<div class="cell" data-execution_count="18">
<div class="cell-output cell-output-display" data-execution_count="18">
<div id="fig-network_graph" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;14: Place/person/book number network of India-related content in <em>Natural History</em></figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-network_graph-output-1.svg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Besides, there are several groups of place names located the edge of the graph, as shown in <a href="#fig-nw_edged_groups">Figure&nbsp;15</a>, indicating they tend to be mentioned together, but relatively distanced from the discussion of India. In most cases India is just a passing metion in the enumerition context.</p>
<div class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<div id="fig-nw_edged_groups" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;15: Example of edged groups in the network graph of India-related text in <em>Natural History</em></figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-nw_edged_groups-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>And there are three obvious person name clusters centering on Book 6, Book 7 and Book 37, the zoomed in captures are shown in <a href="#fig-network_zoom_book6n7">Figure&nbsp;16</a> (for Book 6 and Book 7) and <a href="#fig-network_zoom_book37">Figure&nbsp;17</a> (for Book 37).</p>
<div class="cell" data-execution_count="15">
<div class="cell-output cell-output-display" data-execution_count="15">
<div id="fig-network_zoom_book6n7" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;16: Clusters of Book 6 &amp; Book 7 in India-related content in <em>Natural History</em></figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-network_zoom_book6n7-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>From the cluster of Book 6, the most frequent mentioned historical figures are Alexander the Great and Dionysus (often with a variant name as “Father Liber”), which has been mentioned to be related to the epic and history of conquest from Roman Empire to Indian subcontinent. Also other governers/generals/navigators have significant connectness within the discourse, such as “Juba II”, “Ptolemy II Philadelphus”, “Hippalus”, “Patrocles”, “Leonnatus” etc. And it also show the frequent referred scholars of Pliny in the India-related narratives, for example, “Seneca”, “Eratosthenes”, “Posidonius of Apameia”.</p>
<p>And in the cluster of Book 7, where the discussion focus is on anthropology (human races, tribes, human behaviors), a group of scholars are significantly referred, including “Aristotle”, “Eudoxus of Cnidus”, “Duris”, “Agatharchides”.</p>
<div class="cell" data-execution_count="16">
<div class="cell-output cell-output-display" data-execution_count="16">
<div id="fig-network_zoom_book37" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<figcaption class="figure-caption">Figure&nbsp;17: Clusters of Book 37 in India-related content in <em>Natural History</em></figcaption>
<p><img src="NHthesis_structure_files/figure-html/fig-network_zoom_book37-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>While in the cluster of Book 37, strong edges are connected to Greek scholars, such as “Xenocrates”, “Aeschylus”, “Sudines” and “Zenothemis”. Also there is a significant connectness with “Magi”, referring to the priests in Zoroastrianism, a trditional Persian religion mentioned in the discussion about tales and myths related to the precious stones.</p>
<p>An interesting finding in close reading is that in Book 37, Pliny had addressed direct disprovement to these two groups, with a strong critical attitude. As quoted in the following paragraphs, the Greek scholars and Magus are often mentioned as debatable subjects in Book 37, as a strategy for him to express his own worship of nature and the material world.</p>
<blockquote class="blockquote">
<p>37.11.2 “Here is an opportunity for <strong>exposing the falsehoods of the Greeks</strong>.”</p>
</blockquote>
<blockquote class="blockquote">
<p>37.14.1 “Now I shall discuss those kinds of gemstones that are acknowledged as such, beginning with the finest. And this shall not be my only aim, but to the greater profit of mankind <strong>I shall incidentally confute the abominable falsehoods of the Magi</strong>, since in very many of their statements about gems they have gone far beyond providing an alluring substitute for medical science into the realms of the supernatural.”</p>
</blockquote>
<p>To sum up, the network graph visualizes the connectedness between different types of clustered entities and the central entities within the narrative. In this study, taking the relationship of the place names, person names and book numbers in the target text into consideration, it shows clearly that India is the center of the narrative, and Arabia and Egypt are closely connected to this center. Also, it depicted how the person names of history figures, mythological gods, explorers and scholars are located in the narrative, shedding a light on the structure of the India-related content in <em>Natural History</em>.</p>
<p>If including more types of entities, such as animals, events, ethnic groups, into the network, it will contribute to a more nuanced distance map and entity clustering, which shows more dimensions of the content structure.</p>
</section>
</section>
</section>
<section id="sec-conclusions" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="sec-conclusions"><span class="header-section-number">5</span> Conclusions</h2>
<section id="comprehension-of-india-in-the-narrative" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="comprehension-of-india-in-the-narrative"><span class="header-section-number">5.1</span> Comprehension of “India” in the narrative</h3>
<p>Leading by the research questions of “How is India described, and how is the information about India structured in the work?”, the above analysis of different methods, including word frequency and collocation pattern observation, topic modeling and network analysis, integrating with close reading of the text, comprise a comprehension of “India” in the narrative of <em>Natural History</em>.</p>
<p>Generally, India is regarded as a significant geographical contrast to the Roman Empire and the Mediterranean. It is frequently mentioned for comparison in the description of landscape, expedition, navigating or trading routes and origins of natural creatures and elements of other locations. And the name of rivers in Indian subcontinent, including some tributaries, are given a highlight as references. Another important role of India in the narrative is a major trading partner who frequently import rare and precious treasures into the Mediterranean.</p>
<p>More specifically, the content about India is potentially themed in three topics, integrating with a close reading of the text, these three topics can be illustrated in details. The more prominent topics are the geographical and social condition aobut Indian nations and stones originated and produced in India. In the former topic, inspite of addressing India as a origin for numerous marvels, Pliny incidentally mentioned the epic tales or history related to the conquest of India, which suggest an imperial perspective of the work. And in the less prominent topic, which focused on the merchandise trade, Pliny expressed his criticism about the human greed and unnecessary interference on nature it reflects, which echos his Stoic claim of nature and human world.</p>
<p>And a network of place names, person names and book numbers of the India-related text has been created to depict the focus and co-occurence clusters in the content structure. It shows that Arabia and Ethopia are the two places that close to the mentioning of India in the text, and for different books, there are specific history figures and referencing scholars clustering aroud. And an interesting observation is that in the person name cluster of Book 37, which discussed about the gemstones, Mangus and Geek scholars played an important role as disproving subjects, for Pliny to express his advocate worshiping the genuine nature and material world as a Stoic.</p>
<p>In summary, in Pliny’s unintentional portrait, India showed its complexity as a geographical contrast, an origin of marvels and treasures, a major trading partner, and a context of unecessary luxurious pursuit of Pliny’s contemporary that he debate against in the scope of <em>Natural History</em>.</p>
</section>
<section id="distant-reading-as-a-method" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="distant-reading-as-a-method"><span class="header-section-number">5.2</span> Distant reading as a method</h3>
<p>The attempt of utilizing several distant reading methods for a research of classical text in this study has, to a certain extent, achieved a response to the research question.</p>
<p>From pinning down the research question to conducting a meticulous analysis of the designated text, the application of distant reading methods yielded insightful perspectives and enriched information. However, as shown in the topic modeling section of Data analysis, an integration of close reading is essential in interpreting the outputs of distant reading.</p>
<p>Furthermore, when implementing these methods, data completeness check and validation are crucial steps to be taken before running the analysis. Since the sophisticated textual contents are simplified and restructured as data values in tablular format, it will make big difference for the outcome of missing or mistaken inputs.</p>
<p>Another benefit of adopting the distant reading approaches is the output dataset can be repurposed for subsequent investigations. Together with this thesis, the following dataset and outputs are available on the <a href="https://github.com/lizaodawn/NH_thesis">GitHub repository</a> for potentially re-uses:</p>
<ol type="1">
<li>Dataset of Indian place names mentioned in <em>Natural Hisoty</em> with the coordinating textual passages (scraped from TOPOSText with supplemented mannually checked annotations)</li>
<li>Dataset of geographical names menttioned in <em>Natural History</em> with the coordinating textual passages (scraped from TOPOSText)</li>
<li>Corpus files of textual passages from the <em>Natural History</em> related to India</li>
<li>Network graph of place names, person names and book numbers about India-related contents in <em>Natural History</em></li>
</ol>
<p>Beyond that, the presentation of this thesis is practiced in an integration of <a href="https://quarto.org/">Quarto</a> with jupyter notebook. Embedding the YAML metadata into the notebook, it helped mekke a decent presentation both in HTML and PDF format. With rendering the output in HTML, the interactive maps and graphs can be published online.</p>
</section>
<section id="reflection-and-limitation" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="reflection-and-limitation"><span class="header-section-number">5.3</span> Reflection and limitation</h3>
<p>Though making the best effort to conduct a complete and consistent study for this thesis, there are still some limitation in the data preprocessing and parameter tuning sections that could be enhanced.</p>
<p>As introduced in the Data preparation section, the Indian place names scraped from TOPOSText is found incomplete and gone through a mannual check. About 24% of the amount of orignal retrieved dataset were appended after the mannual check. Though the supplemented Indian place annotation has been updated to the dataset compelling all geographical annotations, there might be missing identifications of places outside the specified coordinates range for India, which is better to also go through a mannual check and suppliment. However, as it requires more effort and time for the scale of the current study, the step has not been taken. It will make the dataset more complete and the context for this study more consistent if the same supplimenting process of all place names could be done.</p>
<p>And for the topic modelling section, when deciding the topic numer and passed for assigning the topics, though there is a validation process for topic number designation, and it aligns with the intuitive observation about differnt outputs, it is better to go through validation other parameters and general comparison for a more validating fine tuning.</p>
<p>On the other hand, with time limitation, it only added person name as an additional entity node for the network analysis. The current network graph shows the distance relationship between person names, place names and book numbers. It may give more dimensions for the whole content structure when including more types of entities, as animals, events, and ethnic groups, which are available on the TOPOSText annotations. In this regard, if the study will continues in the future, this aspect can be certainlly enhanced.</p>
<p>And for the presentation of network graph, alternative platforms should be explored for a more interactive output. The optimal scheme is to make the graph easily zooming in to different clusters, and filtering with different types of nodes.</p>
</section>
</section>
<section id="references" class="level2 unnumbered" data-number="6">


</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">6 References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-akbik2018coling" class="csl-entry" role="listitem">
Akbik, Alan, Duncan Blythe, and Roland Vollgraf. 2018. <span>“Contextual String Embeddings for Sequence Labeling.”</span> In <em><span>COLING</span> 2018, 27th International Conference on Computational Linguistics</em>, 1638–49.
</div>
<div id="ref-bail" class="csl-entry" role="listitem">
Bail, Christopher A. n.d. <span>“Topic <span>Modeling</span>.”</span> Accessed August 3, 2023. <a href="https://cbail.github.io/textasdata/topic-modeling/rmarkdown/Topic_Modeling.html">https://cbail.github.io/textasdata/topic-modeling/rmarkdown/Topic_Modeling.html</a>.
</div>
<div id="ref-barber" class="csl-entry" role="listitem">
Barber, Jordan. n.d. <span>“Latent <span>Dirichlet</span> <span>Allocation</span> (<span>LDA</span>) with <span>Python</span>.”</span> Accessed March 15, 2023. <a href="https://rstudio-pubs-static.s3.amazonaws.com/79360_850b2a69980c4488b1db95987a24867a.html">https://rstudio-pubs-static.s3.amazonaws.com/79360_850b2a69980c4488b1db95987a24867a.html</a>.
</div>
<div id="ref-beagon1996" class="csl-entry" role="listitem">
Beagon, Mary. 1996. <span>“Nature and Views of Her Landscapes in <span>Pliny</span> the <span>Elder</span>.”</span> In <em>Human <span>Landscapes</span> in <span>Classical</span> <span>Antiquity</span></em>, 285–309. Routledge.
</div>
<div id="ref-beagon2011" class="csl-entry" role="listitem">
———. 2011. <span>“Chapter <span>Five</span>. <span>The</span> <span>Curious</span> <span>Eye</span> <span>Of</span> <span>The</span> <span>Elder</span> <span>Pliny</span>.”</span> In <em>Pliny the <span>Elder</span>: <span>Themes</span> and <span>Contexts</span></em>, 71–88. Brill. <a href="https://brill.com/display/book/edcoll/9789004210073/Bej.9789004202344.i-248_006.xml">https://brill.com/display/book/edcoll/9789004210073/Bej.9789004202344.i-248_006.xml</a>.
</div>
<div id="ref-fantoli2022" class="csl-entry" role="listitem">
Fantoli, Margherita. 2022. <span>“Statistics and Linguistics: Can We Tell Something More about <span>Pliny</span> the <span>Elder</span>?”</span> <a href="https://classics-at.chs.harvard.edu/statistics-and-linguistics-can-we-tell-something-more-about-pliny-the-elder/">https://classics-at.chs.harvard.edu/statistics-and-linguistics-can-we-tell-something-more-about-pliny-the-elder/</a>.
</div>
<div id="ref-healy1999" class="csl-entry" role="listitem">
Healy, John F. 1999. <em>Pliny the <span>Elder</span> on Science and Technology</em>. Oxford: university press.
</div>
<div id="ref-kapadia2022" class="csl-entry" role="listitem">
Kapadia, Shashank. 2022. <span>“Topic <span>Modeling</span> in <span>Python</span>: <span>Latent</span> <span>Dirichlet</span> <span>Allocation</span> (<span>LDA</span>).”</span> <em>Medium</em>. <a href="https://towardsdatascience.com/end-to-end-topic-modeling-in-python-latent-dirichlet-allocation-lda-35ce4ed6b3e0">https://towardsdatascience.com/end-to-end-topic-modeling-in-python-latent-dirichlet-allocation-lda-35ce4ed6b3e0</a>.
</div>
<div id="ref-lao2016" class="csl-entry" role="listitem">
Lao, Eugenia. 2016. <span>“Taxonomic <span>Organization</span> in <span>Pliny</span>’s <span>Natural</span> <span>History</span>.”</span> In <em>Greek and <span>Roman</span> Poetry, the <span>Elder</span> <span>Pliny</span></em>, edited by Francis Cairns and Roy Gibson, 209–46. Papers of the <span>Langford</span> <span>Latin</span> <span>Seminar</span> 16. Prenton: Francis Cairns Publications.
</div>
<div id="ref-murphy2003" class="csl-entry" role="listitem">
Murphy, Trevor. 2003. <span>“11. Pliny<span>’</span>s Naturalis Historia: The Prodigal Text.”</span> In, 301–22. BRILL. <a href="https://doi.org/10.1163/9789004217157_012">https://doi.org/10.1163/9789004217157_012</a>.
</div>
<div id="ref-naas2002" class="csl-entry" role="listitem">
Naas, Valérie. 2002. <em>Le Projet Encyclopédique de <span>Pline</span> l’<span>Ancien</span></em>. Collection de l’école Française de <span>Rome</span> 303. Rome: Ecole française de Rome.
</div>
<div id="ref-naas2011" class="csl-entry" role="listitem">
———. 2011. <span>“Chapter <span>Four</span>. <span>Imperialism</span>, <span>Mirabilia</span>, <span>And</span> <span>Knowledge</span>: <span>Some</span> <span>Paradoxes</span> <span>In</span> <span>The</span> <span>Naturalis</span> <span>Historia</span>.”</span> In <em>Pliny the <span>Elder</span>: <span>Themes</span> and <span>Contexts</span></em>, 57–70. Brill. <a href="https://brill.com/display/book/edcoll/9789004210073/Bej.9789004202344.i-248_005.xml">https://brill.com/display/book/edcoll/9789004210073/Bej.9789004202344.i-248_005.xml</a>.
</div>
<div id="ref-neelis2011" class="csl-entry" role="listitem">
Neelis, J. 2011. <span>“Chapter <span>Three</span>. <span>Trade</span> <span>Networks</span> <span>In</span> <span>Ancient</span> <span>South</span> <span>Asia</span>.”</span> In <em>Early <span>Buddhist</span> <span>Transmission</span> and <span>Trade</span> <span>Networks</span></em>, 183–228. Brill. <a href="https://brill.com/display/book/9789004194588/Bej.9789004181595.i-372_004.xml">https://brill.com/display/book/9789004194588/Bej.9789004181595.i-372_004.xml</a>.
</div>
<div id="ref-pinkster2005" class="csl-entry" role="listitem">
Pinkster, Harm. 2005. <span>“The <span>Language</span> of <span>Pliny</span> the <span>Elder</span>.”</span> <em>Journal of Asthma - J ASTHMA</em> 129 (November): 239–56. <a href="https://doi.org/10.5871/bacad/9780197263327.003.0011">https://doi.org/10.5871/bacad/9780197263327.003.0011</a>.
</div>
<div id="ref-pollard2009" class="csl-entry" role="listitem">
Pollard, Elizabeth Ann. 2009. <span>“Pliny’s <span>Natural</span> <span>History</span> and the <span>Flavian</span> <span>Templum</span> <span>Pacis</span>: <span>Botanical</span> <span>Imperialism</span> in <span>First</span>-<span>Century</span> <span>C</span>. <span>E</span>. <span>Rome</span>.”</span> <em>Journal of World History</em> 20 (3): 309–38. <a href="https://www.jstor.org/stable/40542802">https://www.jstor.org/stable/40542802</a>.
</div>
<div id="ref-roller2022" class="csl-entry" role="listitem">
Roller, D. W. 2022. <span>“Introduction.”</span> In <em>A <span>Guide</span> to the <span>Geography</span> of <span>Pliny</span> the <span>Elder</span></em>, 1–14. Cambridge: Cambridge University Press. <a href="https://doi.org/10.1017/9781108693660.003">https://doi.org/10.1017/9781108693660.003</a>.
</div>
<div id="ref-rydberg-cox2021" class="csl-entry" role="listitem">
Rydberg-Cox, Jeff. 2021. <span>“Modeling the <span>Sources</span> and <span>Topics</span> of <span>Pliny</span>’s <span>Natural</span> <span>History</span>.”</span> <em>Umanistica Digitale</em>, no. 11: 217–29. <a href="https://doi.org/10.6092/issn.2532-8816/12521">https://doi.org/10.6092/issn.2532-8816/12521</a>.
</div>
<div id="ref-schultze2011" class="csl-entry" role="listitem">
Schultze, Clemence. 2011. <span>“Chapter <span>Ten</span>. <span>Encyclopaedic</span> <span>Exemplarity</span> <span>In</span> <span>Pliny</span> <span>The</span> <span>Elder</span>.”</span> In <em>Pliny the <span>Elder</span>: <span>Themes</span> and <span>Contexts</span></em>, 167–86. Brill. <a href="https://brill.com/display/book/edcoll/9789004210073/Bej.9789004202344.i-248_011.xml">https://brill.com/display/book/edcoll/9789004210073/Bej.9789004202344.i-248_011.xml</a>.
</div>
<div id="ref-szekely2006" class="csl-entry" role="listitem">
Székely, Melinda. 2006. <span>“Eastern <span>Trade</span> of the <span>Roman</span> <span>Empire</span> Based on <span>Pliny</span> the <span>Elder</span>’s <span>Natural</span> <span>History</span>.”</span> <em>Chronica</em> 6 (January): 199–206. <a href="https://www.proquest.com/docview/2379648941/citation/93A42D142D614235PQ/1">https://www.proquest.com/docview/2379648941/citation/93A42D142D614235PQ/1</a>.
</div>
<div id="ref-talbert2000-1" class="csl-entry" role="listitem">
Talbert, Richard J. A. 2000a. <em>Barrington Atlas of the <span>Greek</span> and <span>Roman</span> World: Map-by-Map Directory</em>. Princeton (N.J.): Princeton university press.
</div>
<div id="ref-talbert2000" class="csl-entry" role="listitem">
———. 2000b. <em>Barrington Atlas of the <span>Greek</span> and <span>Roman</span> World.</em> Princeton (N.J.): Princeton university press.
</div>
<div id="ref-tedeschi2021" class="csl-entry" role="listitem">
Tedeschi, Simone, Valentino Maiorca, Niccolò Campolungo, Francesco Cecconi, and Roberto Navigli. 2021. <span>“WikiNEuRal: Combined Neural and Knowledge-Based Silver Data Creation for Multilingual NER.”</span> In, 25212533. Punta Cana, Dominican Republic: Association for Computational Linguistics. <a href="https://aclanthology.org/2021.findings-emnlp.215">https://aclanthology.org/2021.findings-emnlp.215</a>.
</div>
<div id="ref-tran2022" class="csl-entry" role="listitem">
Tran, Khuyen. 2022. <span>“pyLDAvis: Topic Modelling Exploration Tool That Every NLP Data Scientist Should Know.”</span> <a href="https://neptune.ai/blog/pyldavis-topic-modelling-exploration-tool-that-every-nlp-data-scientist-should-know">https://neptune.ai/blog/pyldavis-topic-modelling-exploration-tool-that-every-nlp-data-scientist-should-know</a>.
</div>
<div id="ref-underwood2012" class="csl-entry" role="listitem">
Underwood, Ted. 2012. <span>“Topic Modeling Made Just Simple Enough.”</span> <em>The Stone and the Shell</em>. <a href="https://tedunderwood.com/2012/04/07/topic-modeling-made-just-simple-enough/">https://tedunderwood.com/2012/04/07/topic-modeling-made-just-simple-enough/</a>.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p><em>Natural History</em> 1.5.1 (<a href="https://topostext.org/work/148" target="_blank">https://topostext.org/work/148</a>)<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>As indicated in the map-by-map directory, the range spans territories of “modern states of India (minus the Punjab), Bangladesh, Bhutan, Burma, Nepal, and Sri Lanka”.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><em>Natural History</em> 37.77.1 (<a href="https://topostext.org/work/153" target="_blank">https://topostext.org/work/153</a>)<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The code for LDA implementation was referred to the tutorial of <span class="citation" data-cites="barber">Barber (<a href="#ref-barber" role="doc-biblioref">n.d.</a>)</span><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>